### ISSUE TITLE
Types in Utilities namespace

### ISSUE THREAD

**Issue by alexandre-mckinnon** [microsoft/perfview#1049]
In the Microsoft.Diagnostics.Tracing.TraceEvent assembly, some types are in the Utilities namespace.

Those types should probably be in the Microsoft.Diagnostics.Tracing.Utilities namespace:

Utilities.Cache<K,T>
Utilities.Command
Utilities.CommandOptions
Utilities.IndexMap
Utilities.OperatingSystemVersion

**Comment by alexandre-mckinnon** [comment]
PR #1062 doing this.

**Comment by twwilliams** [comment]
This causes a big problem for us since we have internal Utilities classes already.

While our classes are in a proper company-named namespace hierarchy, when we end up using OurCompany.Internal in a file (which is most places), when we add a reference to the Microsoft.Diagnostics.Tracing.TraceEvent assembly to our project, none of our Utilities.Whatever() calls can be resolved because this top-level Utilities namespace takes precedence.

**Comment by JpWebster** [comment]
Any chance we could get this change made? We are running into the same issue as reported.

**Comment by brianrob** [comment]
Fixed via #1805.
