### ISSUE TITLE
Request: Dark Mode support of Perfview

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/perfview#1116]
I set Windows 10 2004 (19041) to dark mode for Shell+Apps, but Perfview is still white. 

Can we get Dark mode support in Perfview?

**Comment by brianrob** [comment]
@MagicAndre1981 this is one of those things that is likely going to be left to those in the community.  If it's something that you're interested in contributing, please let me know.  I'd be interested to understand how much work is involved before the work is done just in case it is too invasive.

For now, I will put this on the backlog so that it is available should someone wish to work on this.

**Comment by MagicAndre1981** [comment]
@brianrob I have no idea, as I don't use WPF that much and [Perfview is doing things about UI a bit differently compared to normal WPF applications](https://github.com/microsoft/perfview/blob/b67a385079948d347f42d089670832efaaae46d3/src/PerfView/App.cs#L23), so I have no idea how large the amount of work would be to support themes.

**Comment by rzikm** [comment]
I have been working on this as part of our Hackathon week, and I am interested in getting it "production ready" and merging it later. Can you assign this to me?

**Comment by rzikm** [comment]
Small sneak peek from WIP
![image](https://user-images.githubusercontent.com/32671551/191993420-33a4992f-30af-4165-9301-9b7d5e0a77b8.png)

**Comment by brianrob** [comment]
Absolutely, @rzikm.  Thanks for working on this!
