### ISSUE TITLE
Capturing EventSource with perfcollect

### ISSUE THREAD

**Issue by tmds** [microsoft/perfview#1160]
@brianrob in https://github.com/tmds/Tmds.LinuxAsync/issues/53#issuecomment-596023594 you commented:

> perfcollect is harder to use with EventSource because LTTng doesn't allow for dynamic registration of tracepoints. Instead, all EventSources emit via a single tracepoint called EventSource. Then you can control exactly which events are emitted via an environment variable. It's really not ideal.

What should we do to include events from a specific source when using `perfcollect`?

cc @antonfirsov @adamsitnik

**Comment by brianrob** [comment]
It turns out that there wasn't a great way to get `EventSource` events into a trace file, so I just pushed #1163 to fix this.

You can run `./perfcollect collect <traceName> -events EventSource`

This will enable all EventSources.  You can then filter them by telling the runtime which ones you want.  There are two COMPlus variables for this. 
 See https://github.com/dotnet/runtime/blob/70bfd2ac9b844701c361b90b90ef399ae6fec483/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/XplatEventLogger.cs#L20

**Comment by adamsitnik** [comment]
@brianrob this is great!

@sebastienros could you please update the perfcollect used by aspnet machines?

**Comment by tmds** [comment]
@brianrob thanks!
