### ISSUE TITLE
[Request] nuget package for TraceEvent lib?

### ISSUE THREAD

**Issue by ig-sinicyn** [microsoft/perfview#121]
As Maoni Stephens [just announced](https://blogs.msdn.microsoft.com/maoni/2016/09/19/556/), the TraceEvent now includes API that eases performance-related etw trace analysis.

However, the current version of Microsoft.Diagnostics.Tracing.TraceEvent package (1.0.41) does not include it. Any plans for a new release?

**Comment by vancem** [comment]
Yes, that is something we expect to build a Nuget package out of the PerfView repo soon (it is not hard, we just have many things to do).     Expect it within a week or two. 

In the meantime, you can build this the TraceEvent Dll using the PerfView project, and simply use that DLL in your own project (or refer to it from your own project.  This actually gives a better debugging experience (since your project has complete source code for both your code and TraceEvent).

**Comment by anurse** [comment]
@vancem Will there also be a NuGet package for the .NET Core version? We're looking at using TraceEvent in some performance tracing and right now we're limited to running it in Desktop CLR. If we could have a .NET Core app that worked cross-platform that would be awesome. I realize that TraceEvent currently only supports Windows, but we're already handling the OS pivot and using other tools on Linux, so being able to use a single framework would be really useful :)

**Comment by vancem** [comment]
Yes, there will be a Nuget package for the .NET Core version.   

We actually have have a first shot at compiling TraceEvent for .NET Core (it is in TraceEvent\.NETCore (you will see the TraceEventCore project that builds this directory).  

However this code currently only builds code #ifdefed for the interesting code that works on Linux (TraceEvent supports LTTng on Linux this is what is built).   Turning on the build for windows is pretty straightforward, but we have not done that (Because unlike Linux, you typically can simply run the TraceEvent that runs on desktop if you are on Windows).

Anyway, the plan is in fact to make the TraceEvent package work on .NET Core

**Comment by anurse** [comment]
Cool. We can make it work with the Desktop version for Windows. I definitely would like TraceEventCore on Windows so we can have a single build for both OSes, but that can come later.

**Comment by commonsensesoftware** [comment]
It would also be nice to either scrub all of the library documentation from the NuGet package (since it be hosted here) or split the package into a "normal" and "redist" package like what has been done for EventSource.

**Comment by ig-sinicyn** [comment]
Any updates on this?

**Comment by vancem** [comment]
No progress at this point.    .NET Core is undergoing a rather dramatic change in V2.0 which we hope to ship in a few months.   It makes sense to do this TraceEvent port after that has settled down (which is happening right now, but not completely).   

My expectation is that the best time to do this is still a 1-3 months from now.   Even at that time (when V2.0 has settled down), it is not clear where this work item fits in the priority.

So we can say that it probably makes sense to check back in a month or so.   No promises, but we should at least have a better idea where this fits in the priorities.

**Comment by ig-sinicyn** [comment]
Ok, thanks!

**Comment by MagicAndre1981** [comment]
now that .net core 2.0 is available when can we get an updated NuGet package?

**Comment by vancem** [comment]
Publishing the Nuget package on Nuget.org is on the adgenda   We need to be able to sign it, which has never been done from this repo before.   

In the mean time when you build the TraceEvent directory it DOES create an (unsigned) version of the code. You can use that to unblock until we get the signing worked out.

**Comment by brianrob** [comment]
This should now be resolved.
