### ISSUE TITLE
Debug Assertion Fail for option /NetworkCapture

### ISSUE THREAD

**Issue by yang-er** [microsoft/perfview#1211]
When running `PerfView Collect MyReport /LogFile:MyReport.log /MaxCollectSec:120 /Circular:1000 /BufferSize:1000 /CpuSampleMSec:10 /RundownTimeout:120 /AcceptEULA /SafeMode /NetworkCapture` in an empty folder, it throws an FileNotFoundException.

The call stack is as following:

https://github.com/microsoft/perfview/blob/a88337650be7da672bc17377488e994791405d97/src/PerfView/Utilities/CacheFiles.cs#L69

https://github.com/microsoft/perfview/blob/a88337650be7da672bc17377488e994791405d97/src/PerfView/CommandProcessor.cs#L891

If I place an empty file `MyReport` in the working directory, PerfView will not break up. However, when `/NetworkCapture` is not used, that empty file is not needed.

So why is this empty file needed? Or this is a bug?

**Comment by brianrob** [comment]
@yang-er, I am not able to reproduce this.  `/NetworkCapture` is working properly for me.  The assert that you see here is for the input base file, which is the ETL file that you specify to /DataFile (or specify in the UI).  This file will be created as soon as the session starts, which occurs before this call.

Is it possible for you to capture an ETL trace of the repro that you're seeing?  I am suspecting a race between the file system and session creation, but I would like to be sure before trying to write a fix.

To capture the repro, please use the following command:

`PerfView.exe collect /SessionName:PerfViewRepro /DataFile:PerfViewRepro.etl /NoGui`

Then, once this is collecting, you can run the repro as usual.  Once you've hit the expected behavior, please share `PerfViewRepro.etl.zip`

**Comment by yang-er** [comment]
I'm using the version 2.0.57.0. When running the command given in my original command, it fails

```
...
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
[Error: Could not find file 'MyReport'.]
[DONE 09:35:20 FAIL: PerfView Collect MyReport /LogFile:MyReport.log /MaxCollectSec:120 /Circular:1000 /BufferSize:1000 /CpuSampleMSec:10 /RundownTimeout:120 /AcceptEULA /SafeMode /NetworkCapture]
```

This is the dump file [PerfViewRepro.zip](https://github.com/microsoft/perfview/files/4916041/PerfViewRepro.zip).

However, when I rewrite the command as `PerfView Collect /LogFile:MyReport.log /MaxCollectSec:120 /Circular:1000 /BufferSize:1000 /CpuSampleMSec:10 /RundownTimeout:120 /AcceptEULA /SafeMode /NetworkCapture /DataFile:MyReport.etl`, it succeeded. What is the difference between this two command?

**Comment by yang-er** [comment]
I'm using the version 2.0.57.0. When running the command given in my original command, it fails

```
...
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
[Error: Could not find file 'MyReport'.]
[DONE 09:35:20 FAIL: PerfView Collect MyReport /LogFile:MyReport.log /MaxCollectSec:120 /Circular:1000 /BufferSize:1000 /CpuSampleMSec:10 /RundownTimeout:120 /AcceptEULA /SafeMode /NetworkCapture]
```

I have sent you the Repro zip via mail.

However, when I rewrite the command as `PerfView Collect /DataFile:MyReport.etl /LogFile:MyReport.log /MaxCollectSec:120 /Circular:1000 /BufferSize:1000 /CpuSampleMSec:10 /RundownTimeout:120 /AcceptEULA /SafeMode /NetworkCapture`, it succeeded. Why is the difference between this two command?
