### ISSUE TITLE
Windows ARM64 support for TraceEvent

### ISSUE THREAD

**Issue by adamsitnik** [microsoft/perfview#1264]
To start a `KernelSession` TraceEvent needs to use some of its native dependencies which are architecture-specific. Currently `x64` and `x86` are supported. It would be great if we could add `ARM64` support (and the 32 bit `ARM` variant if possible). 

@brianrob I've access to Windows ARM64 machine (Surface Pro X), I would be very happy to help with implementation and|or testing. 

```cs
using Microsoft.Diagnostics.Tracing.Parsers;
using Microsoft.Diagnostics.Tracing.Session;
using System;
using System.Runtime.InteropServices;

namespace KernelSession
{
    class Program
    {
        static void Main(string[] args)
        {
            if (TraceEventSession.IsElevated() != true)
            {
                Console.WriteLine("You need to run as Admin to be able to use KernelSession!");
                return;
            }

            using (var session = new TraceEventSession(KernelTraceEventParser.KernelSessionName) { StopOnDispose = true })
            {
                session.EnableKernelProvider(
                    KernelTraceEventParser.Keywords.ImageLoad | KernelTraceEventParser.Keywords.Profile,
                    KernelTraceEventParser.Keywords.Profile);
            }

            Console.WriteLine($"Was able to start and stop a KernelSession for {RuntimeInformation.ProcessArchitecture}");
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="2.0.60" />
  </ItemGroup>
</Project>
```

```log
Unhandled exception. System.ComponentModel.Win32Exception (126): The specified module could not be found.
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at KernelSession.Program.Main(String[] args) in C:\Projects\repro\Program.cs:line 20
```

**Comment by brianrob** [comment]
Thanks for bringing this up @adamsitnik.  This is definitely something that I would be interested in seeing done in `TraceEvent`.  I don't think we'll need it in `PerfView`, because `PerfView` will always be in x86 emulation mode on arm64.

If you want to give this a try, it's basically a two-step process.  Step 1 is to include the necessary binaries in the `Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles` nuget package.  This is an internal process, but I can walk you through how to do it.  Once this is done, then you just have to consume the package, and update the `TraceEvent` `csproj` and `nuspec` to include the files.

You can see from my latest updates to these files that it's a somewhat error-prone process, mostly because you have to make sure that the dependencies are in the right place, and that you test on a machine where the dependencies aren't already installed in the `LoadLibrary` search paths.  Happy to help support this work though.

**Comment by adamsitnik** [comment]
The support has been recently added, closing.
