### ISSUE TITLE
Add a command-line generator from the collect/run GUI

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/perfview#1364]
As per @brianrob, this is already implemented here: https://github.com/microsoft/perfview/blob/3e09e663969d8679c6d29a28807d736fd1d2a0e7/src/PerfView/CommandProcessor.cs#L2756

Questions?

1. Should that include the `AcceptEULA` and `NoGUI` arguments?
2. Should that include the path to the currently executing PerfView?

**Comment by brianrob** [comment]
To answer your questions: It is reasonable to include `NoGui`, but I would be hesitant to include `AcceptEULA` because this is a specific statement that each user should make.  I think including the path is really about what the use case is.  Are you going to script something locally, or is this really about handing out command lines to others?  If the former, than you'd want to include it.  For the latter, I think you'd not want to include it.  My gut tells me not to include it, but I'm persuadable.
