### ISSUE TITLE
Consider integrating dotnet trace collection

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/perfview#1365]
Consider integrating `dotnet trace` collection.

**PerfView** is great, not only for analysis, but also for collection.

A curated set of providers like **PerfView** has for **ETW**, would be great to have for `dotnet trace`.

**Comment by brianrob** [comment]
This is an interesting thought.  My inclination is to say that I'd like to not duplicate the functionality, simply because `dotnet-trace` is the one and only tool that does this, and I don't want to try and "keep up" with the great work that they're doing.  But I'm open to be convinced otherwise.  @josalem, @sywhang  what do you think?

**Comment by paulomorgado** [comment]
I don't intend to duplicate `dotnet-trace`, just provide a helpful way for users to visually discover settings and providers and provide a command-line or launch `dotnet-trace`.

**Comment by josalem** [comment]
You effectively want to add `dotnet-trace` as a collecting agent to the `collect` dialogue in PerfView?  That's an interesting thought.  

Nothing stops PerfView from invoking `dotnet-trace` under the covers.  I'm not sure we want to start packaging `dotnet-trace` _in_ PerfView, though.  Would it be sufficient to require the user to install `dotnet-trace` themselves?  This doesn't sound like a great experience for users, though.

Alternatively, PerfView could use the APIs backing `dotnet-trace` directly.  The actual collection code is not that involved (effectively just a call to `Stream.CopyToAsync` or the `EventPipeEventSource` constructor).  Most of the code in `dotnet-trace` goes to building the CLI UI and interactions.

I'm not opposed to the idea so long as we don't start trying to package `dotnet-trace` with PerfView.

**Comment by sywhang** [comment]
I mostly agree with @josalem here and wouldn't be opposed to enabling PerfView to collect EventPipe traces, although I'm not really sure what the benefit of doing this would be, other than being able to collect and analyze the trace from PerfView as opposed to having to launch dotnet-trace from CLI then open up PerfView to analyze it.

> My inclination is to say that I'd like to not duplicate the functionality, simply because dotnet-trace is the one and only tool that does this

`dotnet-monitor` also collects EventPipe traces, so `dotnet-trace` isn't the only tool that does this : )

That being said, I can also see the maintenance cost eventually growing and having to keep two tools in sync to deliver consistent experience being a hassle.

**Comment by paulomorgado** [comment]
Just guiding the user to build the command-line would be a benefit on itself.

Like #1364, this would help build a command-line to run on other machines.

But PerfView could start the process and wait for it to end, but the user would be responsible for have dotnet tools installed.

**Comment by brianrob** [comment]
@paulomorgado, do you think that the most important part is to help folks figure out how to use other collectors more effectively, or is it really about chaining the tools in to PerfView?  The reason I ask is because there are other kinds of tools whose output PerfView knows how to open, but that PerfView doesn't know how to collect.  Examples include perfcollect, vmmap, and Windows process dumps.

Thinking about this a bit more broadly, I'm not sure that I'd want to add collection capabilities for dotnet-trace in PerfView, simply because it doesn't really add any abilities above and beyond what PerfView you could do on Windows.  Said another way, why capture a dotnet-trace collection on Windows when you can capture ETW, unless you're writing cross-platform workflows, and PerfView isn't cross-platform in its current form.

I do think that there is room to make usage of these tools easier, and help to produce useful command lines for collectors.  I'm not sure exactly what it looks like, and would be open to feedback here.

**Comment by paulomorgado** [comment]
It's more about helping the user build the command-line than launching the collection itself.

dotnet-trace still has an advantage over ETW that is collection only for the target process.

**Comment by sywhang** [comment]
@josalem and I would be happy to receive any feedback or suggestions you might have on how we could make the command-line for dotnet-trace easier. Do you have some specific examples of command-lines that are difficult to build out?

**Comment by paulomorgado** [comment]
@sywhang everything about dotnet-trace is difficult if you're used to just run PerfView.

I'd go for an utility tool to just build the helper UI, but the familiarity of PerfView can help users.

**Comment by brianrob** [comment]
I'm going to go ahead and close this issue.  I appreciate the feedback, but at this time, we're not planning on adding dotnet-trace collection support or command line generation to PerfView.  Documentation has been significantly increased for dotnet-trace, and so hopefully that helps folks capture what they need.
