### ISSUE TITLE
Unable to use Heap Snapshot window

### ISSUE THREAD

**Issue by solomon-okolie** [microsoft/perfview#1459]
Using the latest release 2.0.70, I get an error when I try to open the take heap snap shot window. 
Clicking on continue closes the dialog without opening the heap snapshot window.
Existing and restarting Perfview does not prevent this from happening.

Perfview.exe
![Perfview](https://user-images.githubusercontent.com/17110967/125164053-86521a80-e190-11eb-9b2b-b9cc3d71a79d.PNG)

Perfview64.exe
![Perfview64](https://user-images.githubusercontent.com/17110967/125164054-86eab100-e190-11eb-8a26-dbd6f1ab19fe.PNG)

To reproduce

Run Perfview.exe or Perfview64.exe
Click Memory -> Take Heap Snapshot

**Comment by brianrob** [comment]
@solomon-okolie, does this reproduce with earlier versions of PerfView?  My expectation is that it will, and that this is a machine-specific issue.  This is a failure from WMI when trying to get the list of processes on the machine so that the user can pick one to capture a heap snapshot.  I suspect that WMI might be disabled, or that you may not have access to make the query.

It would be interesting to understand the exact issue, but if you are in need to a heap snapshot immediately, you can always capture a full process dump, and then open the dump with PerfView, which will bypass this codepath.

**Comment by solomon-okolie** [comment]
@brianrob correct this has something to do with my PC, I just tried old versions and got the same error. 
However when I clone main and build locally, then run the generated exe I don't get the error but I also don't see any process in the list to pick( so yea something is not right on  my PC).
