### ISSUE TITLE
Perfview 3.0.0-preview2: Throwing System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by AF250329** [microsoft/perfview#1601]
PerfView logging started at 04/04/2022 11:10:33
[EXECUTING: PerfView collect C:\Perfview\Out\DE4C04C48F1A.11-00-54.etl /LogFile:C:\Perfview\Out\DE4C04C48F1A.11-00-54.log /MaxCollectSec:300 /Circular:6656 /CircularMB:6656 /BufferSize:1024 /BufferSizeMB:1024 /Merge:TRUE /Zip:TRUE /RundownTimeout:300 /ThreadTime /TrustPdbs /AcceptEULA /NoView /NoGui]     
[Kernel Log: C:\Perfview\Out\DE4C04C48F1A.11-00-54.kernel.etl]
Kernel keywords enabled: ThreadTime
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Ensuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 32 bit keys.
[Exception Occurred: System.Runtime.InteropServices.COMException (0x80070296): Exception from HRESULT: 0x80070296
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Extensions.ETWControl.EnableStackCaching(UInt64 traceHandle)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)]
[DONE 11:10:33 FAIL: PerfView collect C:\Perfview\Out\DE4C04C48F1A.11-00-54.etl /LogFile:C:\Perfview\Out\DE4C04C48F1A.11-00-54.log /MaxCollectSec:300 /Circular:6656 /CircularMB:6656 /BufferSize:1024 /BufferSizeMB:1024 /Merge:TRUE /Zip:TRUE /RundownTimeout:300 /ThreadTime /TrustPdbs /AcceptEULA /NoView /NoGui]

This exception I get when trying to run Perview from command line. Anything I can do about it ?

**Comment by brianrob** [comment]
@AF250329 a couple of questions about this:

1. Does this repro with the latest 2.x of PerfView?
2. Can you share the machine architecture/OS and whether or not this is a VM, container environment, etc?

Thanks.

**Comment by AF250329** [comment]
@brianrob 

1. Yes - I tried the same command line on Perfview v2.0.68 (the same results)
2. Yes - I am running perfview inside container

**Comment by brianrob** [comment]
Thanks @AF250329.  The reason this is failing is because you are running inside of a process isolation container.  Windows process isolation containers don't support capturing kernel events.  If you want to capture a trace that includes kernel events (e.g. CPU samples, context switches, etc.) then you will want to perform the capture on the host, and make sure to specify `/EnableEventsInContainers` on the command line.  This will cause all events that are emitted inside of a container to flow back to ETW sessions on the host.

The only other option that I'm aware of if you must capture within the container is to convert the container from a process isolation container to a Hyper-V container.  This is effectively a VM and so the kernel won't be shared.
