### ISSUE TITLE
Feature Request - a new Filtering capability for the Events view

### ISSUE THREAD

**Issue by Maoni0** [microsoft/perfview#1629]
The Events view often comes in handy for in-depth perf analysis. However, it can be cumbersome to use when you want to look at events in detail - often you want to do this based on some criteria. For example, if I want to look at CSwitch events in depth along with some GC events that happen on a certain processor, it would be very useful to only show only those events with that ProcessorNumber. Or if I'm only interested in a certain thread and how it gets switched in and out. Of course there are tools that would show you an already processed view of the CSwitch/ReadyThread events. But that processed view may not be exactly what you want and it would be difficult to change it. So being able to filter on the raw events (to be perfectly accurate, the Events view is of course also a processed view but with very little processing) definitely has its own advantages when it comes to looking at events in greater detail. This proposal is to add such a filtering capability to the Events view. This will mostly be used in the "Columns to Display" text box but can also be used in the "Find" text box. I will give a mockup, scenario description and example usage below. 

1) CSwitch analysis –
![filter-Events-view](https://user-images.githubusercontent.com/10837357/167238596-da8ad5bc-ecb6-4989-b5db-166ffcb5f33a.jpg)

I put the filtering expression in []. C++ expressions seem fine for this purpose. Really all we need is some standard ==, >, >=, <, <=, and || and &&. We could consider supporting the “contains” operator. 

If I want to make sure the thread id 1000 is from ABC.exe and not some other process I could do

[((OldThreadID == 1000) && (OldProcessName=”ABC”)) || ((NewThreadID == 1000) && (OldProcessName=”ABC”))] OldThreadID OldProcessName NewThreadID NewThreadPriority OldThreadWaitReason

There may be fields named the same in multiple events so if you want to distinguish the same filed between different you could do 

[(CSwitch::ThreadID == 1000) || …]

So qualify the field with the name of the event (our event names are in general pretty long so we might want to just use the last part which is sufficient for 99% of the cases. 

This gives us a view of how a thread is executing. You could also for example filter based on NewThreadWaitTime >= x to see when it was ready but took a long time to actually got to run. 

Another typical usage for this scenario is to filter based on the processor number so you know the detailed view of what’s running on a specific processor (or multiple specific processors). The Processor view is good for aggregation but sometimes I’d like to see the detail.

UI wise, I think I’d be fine with it if it’s easier to just add another textbox as the Filter for events to display so we don’t have a lot of text in this “Columns To Display” textbox.

Bonus feature – we could enable the same expression for the Find text box. Imagine I already did the above to see how thread 1000 gets switched in and out and I’d like to see when its NewThreadWaitTime was >= x. So I could do [(NewThreadWaitTime was >= x) && (NewThreadID == 1000)]. I could add this to my “Columns to Display” textbox but I may want to get an idea how often it happens so I want to use Find and F3 a few times to see how far apart they are, if such occurrences exist.

2) Allocation analysis –

It’d be helpful to say “I want to see all the objects that are between 1mb and 2mb” – filter would be “[(AllocationAmount >= 1mb) && (AllocationAmount <= 2mb)]” for the AllocTick events (then you can select all of them and do “Open any stacks” to see an aggregation of all the stacks that allocated these objects. 

3) GC analysis – 

“I want to see if there’s a managed memory leak” – filter would be “[Depth == 2] TotalPromoted” for the GCHeapStats event so you can see for gen2 GCs, if the Promoted keeps increasing and if so it means you do have a memory leak.

“I want to see when ephemeral GCs with long pauses” – filter would be “[(Depth < 2) && (DURATION_MSEC >= 30)] DURATION_MSEC TotalPromoted” for GC Start/Stop and GCHeapStats events. If you have CPU samples you can also see the CPU samples during these particular GCs.

I’m sure we can think of other types of analysis that will be made easier with this feature.

I have chatted with @brianrob who also thinks this feature would be very useful when looking at things in detail. Neither he nor I currently has cycles to work on it right now. But he'd be happy to support others if they want to take on this feature.

**Comment by omariom** [comment]
[Dynamic LINQ ](https://weblogs.asp.net/scottgu/dynamic-linq-part-1-using-the-linq-dynamic-query-library)could be used to implement it.
It is available in C# samples/DynamicQuery.

**Comment by MokoSan** [comment]
@brianrob @Maoni0 - if there are no objections, I would like to work on this feature; this is a feature I have always wanted to develop and know that it'll be super useful. Any suggestions / feedback re: the proposal below are greatly appreciated here. 

## Initial Proposed Plan 

### 1.  Parse out the filter query from the Columns to Display Text Box

Using the following regex to match the ``columnSpec`` for any expression within brackets, we get the expression used for filtering (for the sake of consistency, I'll be referring to this expression as the filter query); once obtained we remove it from the original ``columnSpec`` string in order to preserve the current behavior of choosing the desired columns:

```csharp
var escapedMatch = new Regex(@"\[[^\]]*\]");
var matched = escapedMatch.Matches(columnSpec);
columnSpec = escapedMatch.Replace(columnSpec, string.Empty);
```

The spot where I'll be changing this is [here](https://github.com/microsoft/perfview/blob/6a02a08e0b31531de6933304fcab18be52a6708d/src/CSVReader/EventSource.cs#L103). 

### 2. Convert the Filtered Query Into A FilterQueryExpression

The purpose of this stage is to convert the user entered filter query string into an abstraction that represents the collection of predicates called ``FilterQueryExpression`` combined together by boolean operators called ``FilterQueryExpressionTree`` that'll be applied for each ``TraceEvent`` to see if there is a match and if not, that ``TraceEvent`` instance will not be included in the Event View. These abstractions are best explained by an example - for: 

```
[((OldThreadID = "1,000") && (OldProcessName= "ABC")]
```

the 2 corresponding ``FilterQueryExpression``s will be:

1. OldThreadID == "1,000" 
2. OldProcessName == "ABC"

And these two ``FilterQueryExpression``s will be combined with the ``&&`` boolean operator to form the pertinent ``FilterQueryExpressionTree``. 

#### FilterQueryExpression

This abstraction consists of 3 main components of the format: ``LeftOperand Operator RightOperand``. 

The ``LeftOperand`` corresponds to the event and field or just the field that we want to target and could include the name of the event via the scope resolution operator ``::`` such as @Maoni0's example above: ``CSwitch::ThreadID``. 

The ``Operator`` will be one of the following:

```
=, >, >=, <, <=, <>, Contains
```

The ``RightOperand`` can be either a string or a numeric type. 

#### FilterQueryExpressionTree

As stated before, individual ``FilterQueryExpression``s are combined together via the following boolean operators: ```&& ||``` to form a ``FilterQueryExpressionTree``; this abstraction will expose a ``Match`` method that'll be of signature ``bool Match(TraceEvent @event)`` that'll discern if the event should be included in the Event View or not.

This Filter Query Expression Tree will know how to also obey parenthetically enclosed filter query expressions. 

To diagrammatically summarize:

#### The Process

![image](https://user-images.githubusercontent.com/4951960/167321756-152ded04-103c-4433-9dcf-771a615307fc.png)

#### Example Tree

For ```[((OldThreadID = "1,000") && (OldProcessName= "ABC")) || ((NewThreadID = "1,000") && (OldProcessName="ABC"))]```

![image](https://user-images.githubusercontent.com/4951960/167322183-a6457074-1b50-43b6-9818-21952d2a1e87.png)

### 3. Applying the FilterQueryExpressionTree

The code that applies the ``FilterQueryExpressionTree`` can live [here](https://github.com/microsoft/perfview/blob/6a02a08e0b31531de6933304fcab18be52a6708d/src/PerfView/EtwEventSource.cs#L342) with the rest of the filters, in the ``source.AllEvents`` event handler that's called by the ``Update()`` method to update the event view.

**Comment by Maoni0** [comment]
> @brianrob @Maoni0 - if there are no objections, I would like to work on this feature

that'd be great, @MokoSan :)

**Comment by brianrob** [comment]
Yup, no objections at all.  In fact, that would be great.

Overall, I think your plan sounds solid.  A couple of things that came to mind as I was reading through it:

1. I think you will want to do filtering [here](https://github.com/microsoft/perfview/blob/6a02a08e0b31531de6933304fcab18be52a6708d/src/PerfView/EtwEventSource.cs#L329).  It's a few lines higher than you specified in 3 above, but it will allow you to avoid creating an instance of `ETWEvent` when you're not going to display it.  This will also put you above `cnt++`, so events that shouldn't be displayed won't be counted against the maximum events to show.
2. Do you have thoughts on case sensitivity?  In some cases, it might be nice to be able to specify ignorecase.  Not immediatley required, but especially for file paths on case-insensitive file systems, this could be helpful.

Happy to have you start on this when you have time.  I'm available for any issues you run into.  Thank you!

**Comment by MokoSan** [comment]
Thank you, @brianrob! For now, I was thinking about keeping things case sensitive; will take this into account while developing. 

Thanks!

**Comment by MokoSan** [comment]
As a follow-up, I got this working and will be sending out a PR pretty soon after doing some more testing. Here's a demo:

## Demo of Greater + Less Than or Equal to Operators:
https://user-images.githubusercontent.com/4951960/168762353-416a619c-0c2f-4b59-887c-213a7fe2f77f.mp4

## Demo of More Complex Operations With A Bunch of Nesting:
https://user-images.githubusercontent.com/4951960/168765726-f6644215-77e3-4f5a-a70f-a1359a82cdc0.mp4

Some of the queries I demo'd based on the ``GC/Start`` and ``GC/Stop`` events are:
1. ``[(Count > 10 && (Depth >= -1) && (Count <= 30) && (Count <= 30 || ProcessorNumber = 2))] Count ProcessorNumber Depth``
2. ``[(Count > 10  && (Count <= 30) && (Count <= 30 || ProcessorNumber = 2))] Count ProcessorNumber Depth``
3. ``[(Count > 10  && (Count <= 30) && (Count <= 30 || ProcessorNumber = 2))] Count ProcessorNumber``
4. ``[(Count > 10  && (Count <= 30)  && (Count <= 30 || ProcessorNumber = 2))] Count ProcessorNumber``

## Current Limitations / Caveats / Things I Want To Call Out Before Submitting A PR

1. The way I have designed this, I have imposed a restriction of 26 Filter Query Expressions. This is implementation specific and I'll be happy to change this, if need be. The trade-off here was to keep the construction of final RPN expression quick and easy to reduce in the more perf demanding part of the code.
2. To construct an expression, you _have_ to add a space between the Left Operand, Operator and Right Operand. e.g. ``Depth<1`` will not work - instead you'll need to enter: ``Depth < 1``. This is an implementation detail, as well; to construct ``FilterQueryExpression``s, I am splitting on empty spaces to distinguish between the different parts of the expression.
4. I need better error handling and some form of indication to the user that they have constructed an incomplete / incorrect query - would the Status Bar the best place to log these details?
5. Is it worthwhile getting benchmarks / perf testing for this impl? I didn't see anything perf specific in this repo but was planning to use Benchmark.NET to see how the expression processing time changes with increased complexity of sub-expressions.
6. I have created a bunch of unit tests [here](https://github.com/MokoSan/BooleanExpressionParser/tree/main/BooleanParser.UnitTests) that I'll be transferring over the PerfView repo; please let me know if you'd like any other specific testing.
7. I still need to incorporate @Maoni0 's feedback re: adding the ability to filter on different events e.g. ``CSwitch::OldThreadId = 1,000``. 

## Design Details

To build this I prototyped the solution [here](https://github.com/MokoSan/BooleanExpressionParser). In a nutshell, here's what's happening under the hood:

1. We are extracting the expression from the column text box and creating a ``FilterQueryExpressionTree`` based on the different sub-expressions. 
    * A ``FilterQueryExpressionTree`` encapsulates the collection of ``FilterQueryExpression``s and the matching of the trace event on the collection of these expressions. 
2. The algorithm I used to deduce the logical expression is a modification of the [Shunting Yard Algorithm](https://en.wikipedia.org/wiki/Shunting_yard_algorithm) that takes in an infix expression, converts it into it's postfix (aka Reverse Polish Notation (RPN)) equivalent.
3. Once the RPN expression is obtained, I am evaluating it by applying the glue'ing boolean operations to reduce the expression into a single boolean that I return (the ``FilterQueryExpressionTree`` is therefore, not a Tree 😝 - happy to change any of the names, btw!). 

I am super open to any feedback and suggestions! If you'd prefer I create the PR, I'll be happy to do that, as well.

**Comment by Maoni0** [comment]
closing as this was implemented, thanks @MokoSan!
