### ISSUE TITLE
GroupPats: Grouping multiple processes together?

### ISSUE THREAD

**Issue by danieljennings** [microsoft/perfview#1728]
Hi friends, I have a question that I'm guessing has a simple answer (but possibly "sorry that isn't supported").

I have a process ("Parent.exe") I want to analyze that launches many instances of a separate process ("Child.exe"). What I would like to accomplish is a merged view of all of the Child.exe process samples collected, but after several attempts (and several re-readings of the GroupPats documentation) I'm unable to find an incantation that will merge multiple processes together.

If I use the example group pattern `Thread -> AllThreads` to merge the threads together, it will do as you expect - merging the separate threads under one process together, such that each process has an `AllThreads` frame.

But when I try what I expect should be the equivalent for processes - `Process64 -> AllProcesses` - I get a completely empty view (only `ROOT` remains). I've also tried `Process -> AllProcesses` (though my processes are all 64-bit) and that yields no change from the default view (it's as if I have no GroupPats specified).

If I switch to `Process64 => AllProcesses` it (understandably) turns each individual `Process64` frame into an `AllProcesses` frame but doesn't actually merge the processes. Again, this makes sense because each one is a separate entry point from `ROOT`. But then I'm at a loss why the `Process64 -> AllProcesses` version doesn't work to merge the frames together?

Is there something obvious I'm missing here? I figured that grouping processes together would be a common use-case, but I haven't been able to figure out a solution in the separate times I've tried over the last few years.

Thanks,
Daniel

**Comment by brianrob** [comment]
@danieljennings, assuming that you know which processes you want to look at, you should be able to do this fairly easily by opening the view of interest, and then selecting all of the processes that you want to see.  For example, if you open `CPU Stacks`, you'll get something that looks like this:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/6210322/195737429-33d278a1-f2a7-40d1-afe3-7e16abd697fd.png">

You can select multiple processes using CTRL or SHIFT and clicking:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/6210322/195737494-c6d8a37d-b0ce-4657-b5db-797dbe2c3235.png">

If you do this, and then click OK, you'll see that the `IncPats` field in the stack viewer is limiting the set of samples to just the selected processes.  For this example:

```
Process% RuntimeInformationStart (22084)|Process% PerfView (33632)|Process% ServiceHub.RoslynCodeAnalysisService (10480)
```

The most important thing here is that you want to setup the `IncPats`, also known as Include Paths to include just the samples that you want.  `GroupPats` or Group Patterns allows you to group frames, such that they are easier to read, but doesn't actually do any filtering.  `IncPats` should give you what you want.  You can also hand craft the `IncPats` to be something like `Process% Child` and that would include any samples that belong to `Child.exe`.  But, you don't have to hand craft the pattern if you don't want to - multi-selection of processes should do it.  Hope that helps.

**Comment by danieljennings** [comment]
Thank you for the response, @brianrob .

I think you've misunderstood what I was asking for - I'm able to see multiple processes already (thanks to an IncPats filter like you've described) but I want to combine all of their frames together (and then combine all of their threads using the normal Thread -> AllThreads GroupPat).

So for example I want to see one root frame in the flame graph view that is shared by all of the processes selected by the IncPats, and then that one frame would have an AllThreads frame, and then the rest would be the normal flame graph (but representing all of the call stacks across all processes unified).

I would have to synthesize a test program to be able to share screenshots of what I mean, but figuring this out would be valuable enough to me that I'd be happy to take that time if it helps clarify what I mean here, so just let me know.


Thanks again for the time,
Daniel

**Comment by brianrob** [comment]
Ok, I think I understand - Is your goal to just look at the processes that you want to look at, but to not have separate Process or Thread frames.  Assuming I have that right, what's happening is that the include path is getting in your way.  What you want is:

1. Set GroupPats to `Process->AllProcesses;Thread -> AllThreads`
2. Set IncPats to the set of processes that you want to look at.

Unfortunately, when you do this, you get no samples, and the reason is because the include patterns don't match anything because the group patterns have renamed all the process frames.  You can fix this with the following steps:

1. Open the stack viewer that you want (e.g. CPU) and select the processes that you want, so that IncPats gets set properly.
2. Go to the CallTree, right click on the inclusive value of ROOT frame, and select Drill Into.  This will open a new stack window with the same stacks, but you'll notice that IncPats is blank.  That's because the underlying stack source has been filtered.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/6210322/195958143-3406e015-7b57-4aff-bf57-126e3924e720.png">

3. Set GroupPats to `Process->AllProcesses;Thread -> AllThreads`.

Now, you should still be able to see the data, but you'll have a single AllProcesses node, followed by a single AllThreads node.

Let me know if I misunderstood.

**Comment by danieljennings** [comment]
YES! Thank you!!

That totally works, I appreciate your help here a ton. I hadn't realized that IncPats would run after GroupPats but in hindsight it makes complete sense and also explains why I'd end up with an empty result set (which felt weird).

That also led me to discover a related approach that I'll share in case someone else comes across this:
I set GroupPats to `Process64 {%} (->Process $1;Thread -> AllThreads` and then I can set IncPats to `Process Child` and it'll do the merging, group by process name, and then IncPats will filter it to only the (merged) processes named `Child` that I care about.

I super appreciate you helping me out here, PerfView has been my go-to CPU profiling tool for the last few years and this was the one piece I couldn't figure out. I hope you have a great weekend! :)
