### ISSUE TITLE
64-bit build of PerfView

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#175]
### Steps to reproduce

1. Run PerfView with Thread Time enabled
2. Open Thread Time view
3. Set grouping to **[no grouping]**
4. (Sometimes required) Try to switch between views

### Expected results

The application works.

### Actual results

The application crashes after an OutOfMemoryException.

### Additional details

A local 64-bit build showed that use of PerfView regularly used 16+GB of memory for analyzing traces of even a few seconds (5-10 seconds of system time). The application is totally unusable for Thread Time when it fails to load as a 64-bit image.

**Comment by vancem** [comment]
As a work-around you can make your own version of PerfView that is compiled for 64 bit and it is trivial.  You just need to use the 'corflags' utility to turn off the '32 bit preferred' bit on the EXE.   Corflags ships with Visual Studio, but the PerfView repo has a copy of this at src\tools\coreflags.exe 

Thus
     copy PerfView.exe PerfView64.exe
     src\tools\corflags /32bitPref- PerfView64.exe

Will create a version of PerfView the runs as a 64 bit process.   

I have not been proactive about making a 64 bit version of PerfView because it will probably never be a great experience (it will be slow).     It also complicates distribution (I like that it is one exe), and it really does not happen often (I use PerfView alot and the number of OOM I see I can count on one hand).  

Nevertheless, you are not the only person to run into this issue, so I am happy to have the work-around out there, and I am open to the idea of making the 64 bit version more official, it is just that there are so many other things that I think I would do first.   If someone wants to pursue this let me know.  

In the mean time we have the work-around above.

**Comment by sharwell** [comment]
> it really does not happen often (I use PerfView alot and the number of OOM I see I can count on one hand).

I was unsuccessful to produce even a single run of PerfView on my machine that worked without a 64-bit build, even if I only gathered information for a couple of seconds.

**Comment by vancem** [comment]
What exactly are you tracing?    Probably the difference is that you turn off grouping (which makes many more nodes), but there is probably something else about your scenario that causes large memory usage.  

It will be interesting to determine how common your experience is.

**Comment by sharwell** [comment]
> What exactly are you tracing?

Thread time of an asynchronous application (Visual Studio) on a 28-core machine. As opposed to a parallel application, asynchronous applications tend to be very chatty across threads and also have a large number of `Task` instances to track. This is only a best guess.

**Comment by sharwell** [comment]
I found a solution to this which works well after #176 is merged. Since that pull request updates the executable to be an AnyCPU build, all I needed to do was create an executable that contains nothing more than a call to `PerfView.App.Main`, where the executable is *not* marked with the Prefer 32-bit setting. The result is a 12KiB executable that sits next to PerfView.exe for users that wish to make use of it.

There were a few other small items to account for, but I'll send a pull request after we figure out the path forward with #176 and it will all be clear. 👍
