### ISSUE TITLE
Windows SDK upgrade is needed

### ISSUE THREAD

**Issue by OfekShilon** [microsoft/perfview#1752]
README.md says to install Windows 10.0.17763.0 SDK in able to build. This SDK version is no longer available with the VS2022 installer:
![image](https://user-images.githubusercontent.com/73080/202306519-443d36bf-228a-40b1-8a5b-5b031a64e1bb.png)

Similarly, seems .net461 is no longer shipped with VS2022.  Hopefully for Windows 8 and before the existing binaries suffice, and it is possible to upgrade the toolchain.

**Comment by brianrob** [comment]
Thanks for pointing this out.  I've just updated the README - this particular version of the SDK is not required anymore.  The latest version of the Windows 10 SDK is OK.

PerfView and TraceEvent are now built against .NET 4.6.2 instead of .NET 4.5.  .NET 4.6.2 is in support and the targeting pack is part of Visual Studio 2022.  I couldn't find any references to 4.6.1 in the README, but you should be good to build with VS 2022.
