### ISSUE TITLE
NullReferenceException WPA to parse perf log 

### ISSUE THREAD

**Issue by ami-GS** [microsoft/perfview#1780]
Hi Team,

We (MsQuic) are trying to use WPA to visualize perf data.
WPA shows NullReferenceException by loading perf log. I heard the exception comes from perfview from the extension developer.
Could you take a look at from these info?

- https://github.com/microsoft/msquic
- Run on Ubuntu from codespaces
- PerfDataExtension from https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android 
- Test machine side: `perf -F 10 -a -g -o server.perf.data`
- Windows side: `wpa.exe -addsearchdir C:\Users\daikiaminaka\workspace\Microsoft-Performance-Tools-Linux-Android\PerfDataExtensions\bin\Debug\netstandard2.1\`
- Attached is the entire log from Diagnostic Console on WPA. I believe the System.NullReferenceException at the end come from perfview.
[WPA_PerfDataExtension.txt](https://github.com/microsoft/perfview/files/10378189/WPA_PerfDataExtension.txt)

**Comment by brianrob** [comment]
@ami-GS, looking at the log, it does appear that the exception is thrown in TraceEvent code.  Can you please share `file:///C:/Users/daikiaminaka/Downloads/root/QUICLogs/msquicperf3/server.perf.data.txt`?  That will make this much easier to repro.

**Comment by ami-GS** [comment]
Newly taken, but I confirmed NullReferenceException happens
[Uploading msquicperf3.perf.data.txt…]()

**Comment by ami-GS** [comment]
file could not be uploaded for some reason. (Github bug?)
Let me share the file in internal channel

**Comment by ami-GS** [comment]
file uploaded!
[msquicperf3.perf.data.txt](https://github.com/microsoft/perfview/files/10467051/msquicperf3.perf.data.txt)

**Comment by brianrob** [comment]
@ami-GS, apologies for the delay.  It looks like this is actually the raw `perf.data` file, and not the `perf.data.txt` file that TraceEvent knows how to consume.  Can you confirm that this is actually the file that is being opened?  If so, that's the reason that this isn't working.

**Comment by ami-GS** [comment]
Let me double check, but what file you expect? the one after applying `stackcollapse-perf.pl`?

**Comment by brianrob** [comment]
Looking at your repro steps again, I anticipate the issue is that you need to convert the perf.data file that gets collected on the Linux machine to a perf.data.txt file, which is done via the `perf script` command.  I'm not sure what the instructions are for capturing traces to view in WPA, but if TraceEvent is being used underneath, which I understand to be the case, then TraceEvent doesn't know how to read anything but the output of `perf script`.  I suspect you need to run `perf script -i <inputfile> -F comm,pid,tid,cpu,time,period,event,ip,sym,dso,trace > perf.data.txt` and then use the resulting file.

**Comment by ami-GS** [comment]
I could visualize with the output from `perf script`... there was no issue.
Thanks for your help!
