### ISSUE TITLE
.NET event dispatch method shows as ?!? in call stacks

### ISSUE THREAD

**Issue by sharwell** [microsoft/perfview#188]
I just noticed a case where the event dispatch method shows as **?!?** in PerfView. In the following image, the two `HandleHunksChanged` methods are listeners attached to an event, and `OnHunksChanged` is a method that raises the event. It would be nice if the presentation of the invocation method was improved.

![image](https://cloud.githubusercontent.com/assets/1408396/25868850/cc95167e-34c3-11e7-8952-81181eeabc67.png)

**Comment by vancem** [comment]
Generally for specific bugs we will typically need a data file (ETL.ZIP file) as well as enough information to find the stack in the trace (typically a timestamp or a stack trace), so that it can be located again.  

These files are big enough that dragging them into the Issue may not be a good idea (I don't know what limitations Github has on that).   If necessary we may wish to set up some drop location (within Microsoft using a directory under \\clrmain\public\writable is reasonable.  

It is not unusual for the issue to be associated with data generation (which needs runtime/OS changes) rather than PerfView changes).

**Comment by brianrob** [comment]
Closing this as we would need the ETL to make progress on this.
