### ISSUE TITLE
Parsing CTF trace file fails because of wrong event_id lookup for DotNETRuntime:EventSource

### ISSUE THREAD

**Issue by cincuranet** [microsoft/perfview#1911]
Assume event like this (from `babeltrace`) (Note: This is vanilla EventSource event, not event that goes through custom LTTng provider we use in _perf lab_ for Ubuntu 22.04.):

```
DotNETRuntime:EventSource: { cpu_id = 62 }, { vpid = 13077, vtid = 13077, procname = "emptyvbconsolet" }, { EventID = 6668, EventName = "OnMain", EventSourceName = "PerfLabGenericEventSource", Payload = "" }
```

The `EventID` here is `6668`. But the `CtfReader` is using this id [here](https://github.com/microsoft/perfview/blob/main/src/TraceEvent/Ctf/CtfReader.cs#L185) to do the array indexing. Because at this point the `_streamDefinition.Events` contains only one event definition (for the one above), the indexing fails.

Looks like the lookup/indexing should involve ID and `CtfMetadataLegacyParser` should handle that as well. But I'm still deciphering this.

**Comment by brianrob** [comment]
If I understand correctly (and I'm not sure I do, so please correct me if I'm wrong), you are wondering why the event ID in the metadata doesn't match the EventID field in the event.  This is because the EventID field in the event is determined at runtime by the EventSource implementation, while the ID in the metadata document is an ID assigned by lttng-ust and won't change based on the EventSource event.

I've had a long standing desire to deserialize the data in the EventSource event and then use it to dispatch the event directly to the correct callback, but this isn't something that we've ever attempted to implement.

**Comment by cincuranet** [comment]
What's "bit different" is that the event uses extended header (below output from "debug" `babeltrace`). Maybe that's confusing the reader. Still investigating.

```
timestamp = 14:06:07.310512837, delta = +0.074179155, trace = /mnt/tmp/Startup_-_Static_Console_Template_-_FDD_Publish_startup.trace/Startup_-_Static_Console_Template_-_FDD_Publish_startup.trace/lttngTrace/auto-20230921-050606/ust/uid/1001/64-bit, trace:hostname = dotcjade-14, trace:domain = ust, loglevel = TRACE_DEBUG_LINE (13), name = DotNETRuntime:EventSource, stream.packet.context = { timestamp_begin = 482332244290775, timestamp_end = 482332968987133, content_size = 2064, packet_size = 32768, packet_seq_num = 0, events_discarded = 0, cpu_id = 14 }, stream.event.header = { id = ( "extended" : container = 65535 ), v = { extended = { id = 0, timestamp = 482332675464150 } } }, stream.event.context = { vpid = 614568, vtid = 614568, procname = "staticconsolete" }, event.fields = { EventID = 6668, EventName = "OnMain", EventSourceName = "PerfLabGenericEventSource", Payload = "" }
```
