### ISSUE TITLE
FinalizeObject event has a type ID, but not a type name

### ISSUE THREAD

**Issue by sharwell** [Microsoft/perfview#200]
This may be difficult to implement, but it would be exceptionally valuable for understanding these events.

### Steps to reproduce

1. Open **Events** view
2. Select the **Microsoft-Windows-DotNETRuntime/GC/FinalizeObject** event
3. Click **Cols**

### Expected result

Two options for columns would be **TypeID** and **TypeName**.

### Actual result

The column **TypeID** is available, but **TypeName** is not.

**Comment by vancem** [comment]
The FinalizeObject event used to be on a special ClrPrivate provider.  This event DOES have the type name associated with it   Thus if you collect the data with /Providers=ClrPrivate turned on you will get this event and **you can get the data you want in the very short term**.

The Clrprivate provider is now mostly considered legacy as in theory the interestting events from that provider have been moved to the CLR provider.    However when this was done the TypeName fields was dropped from the FinalizeObject. 

Instead it use the 'Type/BulkType' event to define the typeID->TypeName mapping (This has the advantage that you only need to log these mapping events once per trace, rather than once per event.  

This is very much like what happens for FileName fields on read or write events.    Only the Handle is in the event, but there is another event that maps the handle to the name.     This needs to be done for this event.     

Thus there is an 'expected' way of fixing this.   If anyone wants to fix this, it would be great, but check with me before doing any significant coding so we are on the same page.

**Comment by sharwell** [comment]
@vancem I don't see any Type/BulkType events in the trace I'm looking at. Is this something that needs to be explicitly enabled?

**Comment by vancem** [comment]
You do have to turn on the events by on (It is the ClrTraceEventParser.Keywords.Type keyword of the CLR provider).   PerfView does this by default, but the VS RPS system may not)

Note that I have not personally tested this end-to-end.

**Comment by sharwell** [comment]
Thank you. It may take some time for me to come back to this but I do plan on it. :smile:

**Comment by sharwell** [comment]
This was fixed by #237.
