### ISSUE TITLE
Error in opening Perf profile trace that complaining a concurrent update was performed

### ISSUE THREAD

**Issue by qizhang15** [microsoft/perfview#2063]
I try to open a Perf profile trace using WPA but keep getting the following error. I tried different WPA versions, not helping. The Linux Perf plugin version is 1.2.4. The error says, "A concurrent update was performed on this collection and corrupted its state".

![Error](https://github.com/user-attachments/assets/7629a201-afe2-4ec9-ad56-ce7ed2dba111)

Ivan got the stack of exception and it shows from our "3rd party" TraceEvent lib that processes the file.

![Exception](https://github.com/user-attachments/assets/04157514-c8de-482a-b20c-6d1ba027eeda)

**Comment by brianrob** [comment]
This appears to be caused by multiple callers into the same `LinuxPerfScriptStackSource`, which is not supported.  Are you able to see why there are two threads touching this object at the same time?  The exception comes from a `Dictionary` lookup that occurs during a write operation into the same `Dictionary`.  I am wondering if this is an issue in the plugin rather than `LinuxPerfScriptStackSource`.

**Comment by ivberg** [comment]
I can debug more to see if this is happening. However it should not be AFAIK. @qizhang15 can you test your file with PerfView GUI to see if this issue repros there as well?

**Comment by brianrob** [comment]
Thanks @ivberg. We can certainly protect that Dictionary with a lock, but I would love to understand the use before we do anything like that.

**Comment by ivberg** [comment]
Verified fixed manually using trace supplied by @qizhang15 . Thx @brianrob  for the quick fix!

**Comment by brianrob** [comment]
> Verified fixed manually using trace supplied by @qizhang15 . Thx @brianrob for the quick fix!

Excellent.  Thanks for reporting.
