### ISSUE TITLE
Revisiting PerfView/PerfView64

### ISSUE THREAD

**Issue by sharwell** [microsoft/perfview#325]
Following some (minor, and now resolved) confusion about the PerfView and PerfView64 artifacts that get attached to the AppVeyor builds, I wanted to revisit the separation of these binaries. During the discussion of #175, the concern for unification appeared to be the performance impact of running in 64-bit mode when not necessary. However, my overall observation regarding PerfView performance has been the following:

1. Trace files which are small enough to load in the 32-bit build do not face performance problems in either the 32-bit or 64-bit builds.
2. Trace files which encounter performance problems cannot load successfully in the 32-bit build, thus any potential performance advantage of it is moot.

It appears that the current separation of these binaries does not provide performance-related value to end users. It would make sense in this case to simplify the build by releasing only a single binary, which is an AnyCPU build with the Prefer 32-bit flag set back to false.

**Comment by pharring** [comment]
It'd be nice to put this issue to bed once and for all.
Can we back up your observations with (non-subjective) data?
Presumably, we need a trace that is small enough to fit 32-bit, but large enough to generate meaningful timing metrics.

**Comment by sharwell** [comment]
@pharring Currently this is only a perspective observation. I rarely have a trace that fits in the 32-bit process (typically only happens if I'm trying to make that happen specifically). When I do see performance problems using smaller traces, I find that it indicates a bug in PerfView () more than indicating a case where the 64-bit version is slower.

The weakest point in my argument is the 64-bit version requires more physical memory in order to load the same trace. However, it does not seem like an unreasonably limiting assumption that developers assigned to performance investigations will have systems where an additional 3.5GiB (at the very most) of additional memory in use for the investigation will cause substantial problems.

**Comment by vancem** [comment]
For what it is worth, my experience is exactly the opposite.   I can count on one hand the number of times I have needed a 64 bit version of PerfView, and I do a lot of performance investigations.     My guess is that using 64 bit when you don't need to will cost you 10-20% in throughput (because caches are used less efficiently this is what it costs servers to go from 32 to 64 bit).   This is not huge from a human perspective, but it certainly is not pay for play.  

There is another argument that says, that frankly that any time you are manipulating GB of data, things will not be fast.   It would be (much) BETTER if we can invest in keeping the data smaller (probably mostly through sampling or reprocessing).   It really should be the case that MOST scenarios don't need HUGE amounts of data for you to do an effective performance analysis.   I would like that option thoroughly explored before we give up and say you need 4GB+ traces routinely to get the job done.  

Now that said, I understand that until we do that, there are people who have the issue today.   That is why I was OK with the 64 bit build.   I am even OK making it so that PerfView can relaunch itself as a 64 bit app, and even making this so that particular users can make it do that by default.   PerfView already had to know how to relaunch itself (for elevation, and to avoid locking files on file shares), so doing this is pretty easy.     

I do understand that making just one build is simpler, but I would want some non-trivial data that shows a non-trivial part of the user base is running into the issue 

If you get 50+ bonafide perfView users giving a thumbs up on this issue, that would certainly get my attention (I would look into reducing memory consumption and if that failed, I would make 64 bit the default).

**Comment by davkean** [comment]
I've given up using the 32-bit version of PerfView. Even if there is a performance impact (which anecdotally I haven't noticed), I find it easier to have a single version than guessing whether or not the 32-bit version is going to OOM or not. 

It does feel like we're on different sides of the world though, almost all my traces are huge - maybe I'm missing something to reduce the traces that I'm looking at? Almost all performance issues that I'm investigating are due to huge solutions and find it easier and better timewise to quickly grab a trace and investigate those than breaking the repro down to something manageable.

**Comment by vancem** [comment]
I don't have a problem with you using PerfView64 all the time.   By all means do so, that is what it is for.  

Ideally we would figure out ways of getting your scenarios to NOT need GBs of memory (since I think that should be possible and would significantly improve your experience (it would be faster)), but I am not actively looking at that, so using PerfView64 is fine.

**Comment by mahamr** [comment]
Was just perusing old issues, seems this one can be closed since PerfView 3.x is now 64bit only?

**Comment by brianrob** [comment]
Yup, thanks @mahamr.
