### ISSUE TITLE
PerfView project load failed

### ISSUE THREAD

**Issue by shimingsg** [Microsoft/perfview#362]
Duplicated linked item found in the project: "native\x86\sd.exe"
checked that there are 2 place of sd.exe included:
`<None Include="$(PerfViewSupportFilesBase)native\x86\sd.exe">
      <Link>x86\sd.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>False</Visible>
</None>`

`<EmbeddedResource Include="$(PerfViewSupportFilesBase)native\x86\sd.exe">
      <Type>Non-Resx</Type>
      <WithCulture>false</WithCulture>
      <LogicalName>.\x86\sd.exe</LogicalName>
      <Link>x86\sd.exe</Link>
</EmbeddedResource>`

**Comment by sharwell** [comment]
@vancem I can reproduce this on 15.2. Now that 15.3 is released, we have two reasonable options:

1. Require Visual Studio 2017 Update 3 (15.3) for this solution, since we know it works better with the new project system and .NET Standard 2.0.
2. Find a way to work around the issue and continue allowing 15.2.

Let me know which you prefer (I don't want to spend too much time on the second if the first is acceptable).

**Comment by vancem** [comment]
Do we know why this only happens for the sd.exe?  (There are other native DLLs that are basically the same).  Is it because it is an EXE?   

It sounds like it is catastrophic (you can't load in VS).  That is pretty unfortunate.    

It turns out that we could remove the one that copies to the output directory without much impact (it would mean that when you run in the debugger and try to use source code lookup that needs source depot (basically windows source), it will not work.   That is not a big deal (because it is only when it is in the debugger).  

Can msbuild detect the exact version of VS running?   

My recommendation is to comment out the second use of sd.exe for now, but log an issue for say 1 year from now to put it back, and to make msbuild fail more obviously if you try to use something earlier than 15.3.

**Comment by sharwell** [comment]
> There are other native DLLs that are basically the same

It seems an exception is thrown at the first detected occurrence of this. Fixing this one may reveal other files that result in the same error. If we fix it, all cases would need to be fixed.

> It turns out that we could remove the one that copies to the output directory without much impact

I'm testing a solution which eliminates the `Link` metadata for one of the references. Will submit a pull request if it works.
