### ISSUE TITLE
PerfView.sln requires .NET Standard 2.0

### ISSUE THREAD

**Issue by pharring** [microsoft/perfview#365]
On a clean machine, install VS 2017 and try to build PerfView.sln

TraceEvent.csproj fails to build because:
>C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): error : The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.

Looks like I need to download and install the .NET Core 2.0 SDK: https://www.microsoft.com/net/core#windowscmd

Should this be in the readme?

**Comment by sharwell** [comment]
@jaredpar How are we approaching (or planning to approach) this issue for Roslyn?

**Comment by jaredpar** [comment]
@sharwell the act of migrating to SDK 2.0 or how to communicate to the developer our dependency? 

In terms of migrating to SDK 2.0 the work is all being done on the [features/sdk2](https://github.com/dotnet/roslyn/tree/features/sdk2) branch. It's a lot of work and the current active PR is the largest change that will prob take another day or two to complete. 

In terms of communication. I'm hooking the "BeforeBuild" target in dotnet/roslyn to catch this, and provide a link to the SDK that needs to be downloaded. Unfortunately that is the best we can do for 15.3. The SDK is not chained into the VS install hence it has to be a separate download. I can't even bootstrap it via Restore.cmd because in order for the SDK to function it has to be a part of `%PATH%`. :(

**Comment by sharwell** [comment]
@jaredpar I believe the primary issue for us will be the communication issue. I'll watch for the way you hook the build to catch this and implement something similar for PerfView once we're happy-ish with the outcome.

**Comment by brianrob** [comment]
This is now in the README, so closing.
