### ISSUE TITLE
Run perfview in Microsoft/asp.net core:1.1.2-nanoserver docker container 

### ISSUE THREAD

**Issue by EVMartinez** [microsoft/perfview#367]
Are there any plans to support/port perfview to run on nanoserver docker container?

**Comment by vancem** [comment]
Sorry for the delay.    There are not plans particularly for this at present, however the doing something here is actually not hard.     In particular  the TraceEvent library (which does all the real work), does now work on .NET Core (which is what runs on Nanoserver).    PerfView has all the view (GUI logic), so we don't want to actually try to port it, but we could use TraceEvent to make a command line version of the collector.  Indeed the PerfView code is already factored in a way that should make this straightforward.  

If there is interest, I can give advice about how exactly to go about doing this.

**Comment by EVMartinez** [comment]
Hello Vance,

I just asked to another 3 friends and they will be thrilled to work in this task too, so what do we need to get started?

Regards!


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Vance Morrison <notifications@github.com>
Enviado: miércoles, 4 de octubre de 2017 04:11 p. m.
Para: Microsoft/perfview
CC: EVMartinez; Author
Asunto: Re: [Microsoft/perfview] Run perfview in Microsoft/asp.net core:1.1.2-nanoserver docker container (#367)


Sorry for the delay. There are not plans particularly for this at present, however the doing something here is actually not hard. In particular the TraceEvent library (which does all the real work), does now work on .NET Core (which is what runs on Nanoserver). PerfView has all the view (GUI logic), so we don't want to actually try to port it, but we could use TraceEvent to make a command line version of the collector. Indeed the PerfView code is already factored in a way that should make this straightforward.

If there is interest, I can give advice about how exactly to go about doing this.

**Comment by vancem** [comment]
Great.   It is probably easier for me to do the initial stab at making the .NET Core version, and then you can try it out, and do anything that I can hand off to you.    Pester me on Friday if I have not gotten back to you.

**Comment by EVMartinez** [comment]
Thank you! I agree with your approach.

Regards!

Sent from my iPhone

On Oct 4, 2017, at 7:05 PM, Vance Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:


Great. It is probably easier for me to do the initial stab at making the .NET Core version, and then you can try it out, and do anything that I can hand off to you. Pester me on Friday if I have not gotten back to you.

**Comment by vancem** [comment]
I have created the following branch 

https://github.com/Microsoft/perfview/tree/PerfViewCollect.10-5-17

This branch has a new project called 'PerfViewCollect' which is a command line version of PerfView (basically all the command line options which are enough to do all collection).   You can run it (to collect a default PerfView trace) by going to the bin\Debug\netcoreapp2.0 directory and typing
```
dotnet PerfViewCollect.dll collect
```
Note that the ;deploy as single EXE does not work at the moment (you have to deploy the whole directory), and there are probably a fair number of rough edges (only ETW collection works, getting heap dumps and some /DotNet* options don't work).  

I have not tested it on Nano at all (I don't see why it would not work, but who knows).   

I did not check this in because I hate the number of ifdefs in the current code.   I want to think about it.   

But you can certainly test it out.

**Comment by EVMartinez** [comment]
I'll give it a try!

Sent from my iPhone

On Oct 5, 2017, at 5:40 PM, Vance Morrison <notifications@github.com<mailto:notifications@github.com>> wrote:


I have created the following branch

https://github.com/Microsoft/perfview/tree/PerfViewCollect.10-5-17

This branch has a new project called 'PerfViewCollect' which is a command line version of PerfView (basically all the command line options which are enough to do all collection). You can run it (to collect a default PerfView trace) by going to the bin\Debug\netcoreapp2.0 directory and typing

dotnet PerfViewCollect.dll collect


Note that the ;deploy as single EXE does not work at the moment (you have to deploy the whole directory), and there are probably a fair number of rough edges (only ETW collection works, getting heap dumps and some /DotNet* options don't work).

I have not tested it on Nano at all (I don't see why it would not work, but who knows).

I did not check this in because I hate the number of ifdefs in the current code. I want to think about it.

But you can certainly test it out.

**Comment by vancem** [comment]
I have merged this into the master branch, however PerfVIewCollect is NOT in the solution at the moment.  (checkin tests seem to have a problem with it)   Until I get that resolved you have to add the PerfViewColllect.csproj to the solution locally

**Comment by EVMartinez** [comment]
I did tried to run perfviewcollect.dll in the following docker image microsoft/aspnetcore:2.0.0-nanoserver, I got the following error:

VERBOSE LOG IN: PerfViewData.log.txt
EXECUTING: PerfView Collect

Pre V4.0 .NET Rundown enabled, Type 'D' to disable and speed up .NET Rundown.
Type S to stop collection, 'A' will abort.  (Also consider /MaxCollectSec:N)
Kernel Log: C:\Users\ContainerAdministrator\Documents\perfview\Debug\netcoreapp2.0\PerfViewData.kernel.etl
DONE 22:59:18 FAIL: PerfView Collect

Seems that is looking for some full framework dependency, I tried in another with full framework and it worked.



Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Vance Morrison <notifications@github.com>
Enviado: lunes, 9 de octubre de 2017 02:17 p. m.
Para: Microsoft/perfview
CC: EVMartinez; Author
Asunto: Re: [Microsoft/perfview] Run perfview in Microsoft/asp.net core:1.1.2-nanoserver docker container (#367)


I have merged this into the master branch, however PerfVIewCollect is NOT in the solution at the moment. (checkin tests seem to have a problem with it) Until I get that resolved you have to add the PerfViewColllect.csproj to the solution locally

**Comment by vancem** [comment]
There should be extra information in the PerfViewdata.log.txt file that it generates.   Can you pass it along.

Vance


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by pharring** [comment]
What's the progress here? I have a need to do some profiling of an app in a nanoserver container and it would be handy to have this.

**Comment by vancem** [comment]
Hello Paul,

I have made not progress that is not logged here, but mostly because I need data from a Nano run to understand what need to change (it is likely to be easily fixable).  I will make an attempt today to get some data (run it in a Nano container), but if you have one set up already and can simply try it (and give me back the PerfVIewData.log.txt file) that would move things along.

**Comment by pharring** [comment]
I can't even get PerfViewCollect.dll to run:
```
Error:
  An assembly specified in the application dependencies manifest (PerfViewCollect.deps.json) was not found:
    package: 'Microsoft.Diagnostics.Tracing.TraceEvent.SupportFiles', version: '1.0.8'
    path: 'lib/netstandard2.0/Dia2Lib.dll'
```

I suspect a problem with support file extraction because I don't see a PerfViewCollect folder created in %APPDATA%.

This is on a Windows Server 10 Enterprise (1709) host running a `microsoft/dotnet:2.0.0-runtime-nanoserver-1709` container. I mapped the whole of my PerfView enlistment (on D:\PerfView) into the container:

`docker run -it --rm --volume=D:\PerfView:C:\PerfView microsoft/dotnet:2.0.0-runtime-nanoserver-1709`

**Comment by vancem** [comment]
I have made a self-contained copy of PerfCollect at \\vancem1\public\PerfCollect.   You can map that drive and run it (that is what I did).    You can make your own self-contained version by running
```
dotnet publish --self-contained -r win-x64 
```
In your PerfView\src\PerfViewCollect directory.  

However you need not bother just now.  I was able to run this on Nano, and it fails because the ETW session start fails.   I suspect that is happening is that Nano does not support some legacy ways of starting kernel sessions that PerfView happens to use.   I am looking into this now...

**Comment by pharring** [comment]
Thanks for the "dotnet publish" tip. I'm at the same stage as you now.

**Comment by vancem** [comment]
Paul:

Do you know if you have to do something in nano to be admin?   It is failing because of ‘Accessed Denied’, which MAY be because I am not admin, but I don’t know how admin works in Nano/Containers (I thought you were always admin, but I don’t know).

Thanks

Vance

**Comment by ladeak** [comment]
Are there any updates on this? I am getting a little confused on this topic: perfview release 2.0.2 says it supports Containers. When I try to run it in a Container on Nano server (microsoft/dotnet:2.0-runtime-nanoserver-sac2016) just nothing seems to happen.

**Comment by vancem** [comment]
When PerfView 2.0.2 says it supports containers, it means it supports Windows Server Containers (see https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/#windows-container-types)   Virtual machines (whey they call Hyper-V Isolation was already supported because it was a full Windows Kernel running in the container).   In order to run PerfView however, you have to have a full .NET Runtime on the machine, which implies a normal Windows OS running in the container.  

Nano Server is a stripped down Windows OS and does not support the full .NET Runtime.    It does however support .NET Core, and in the PerfView repository there is a stripped down version of PerfView called PerfVIewCollect that DOES run on .NET Core (it is built as part of a normal build of the PerfView repository, but you can create a self-contained version as indicated in my comment above).  

Things have not changed since I wrote last October.   We are probably very close The application works fine on non-nano OSes but at last check fails on nano OSes.   It may be easy to fix but I have not looked at it since October.

**Comment by brianrob** [comment]
My understanding is that this should now work on nano.  I'm going to close this issue, but please do open a new issue with details if you run into any issues.  Thanks.

**Comment by kayle** [comment]
Search engines lead to this issue when hitting 'access denied', so adding that the fix is to run ```docker exec -it --user ContainerAdministrator <container name> pwsh``` to start an elevated powershell in a nanoserver container.

Unfortunately, I still don't get symbols for some native dlls that are in the container (running 20H2 update):
```
[Looking up symbols for coreclr]
[Loading symbols for \\?\vmsmb\vsmb-{dcc079ae-60ba-4d07-847c-3493609c0870}\fc9d817f-0db7-5187-b881-30788288ba13\files\program files\dotnet\shared\microsoft.netcore.app\5.0.0\coreclr.dll]
No PDB signature for \\?\vmsmb\vsmb-{dcc079ae-60ba-4d07-847c-3493609c0870}\fc9d817f-0db7-5187-b881-30788288ba13\files\program files\dotnet\shared\microsoft.netcore.app\5.0.0\coreclr.dll in trace.
```

I can workaround using UnsafePDBMatch, but it'd be nice to fix this. Interesting that Windows kernel dlls are working now, so that's an improvement from the 1803 issues mentioned in the Users Guide. PerfViewCollect could potentially workaround the problem by eagerly resolving these symbols at the end of the merge operation and including them in the .zip file.

Here's some of the broken dlls:
```
Event Name | Time MSec | Process Name | FileName
Windows Kernel/Image/DCStart | 16.907 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\43987C9A-60FF-5CA8-AC39-92766C01D4D1\Files\Program Files\powershell\.store\powershell.windows.x64\7.1.0-rc.2\powershell.windows.x64\7.1.0-rc.2\tools\net5.0\any\Modules\PSReadLine\Microsoft.PowerShell.PSReadLine2.dll
Windows Kernel/Image/DCStart | 16.947 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\Microsoft.DiaSymReader.Native.amd64.dll
Windows Kernel/Image/DCStart | 17.214 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\clrcompression.dll
Windows Kernel/Image/DCStart | 17.551 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\clrjit.dll
Windows Kernel/Image/DCStart | 17.559 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\coreclr.dll
Windows Kernel/Image/DCStart | 17.560 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\hostpolicy.dll
Windows Kernel/Image/DCStart | 17.563 | pwsh (956) | C:\Device\vmsmb\VSMB-{dcc079ae-60ba-4d07-847c-3493609c0870}\FC9D817F-0DB7-5187-B881-30788288BA13\Files\Program Files\dotnet\host\fxr\5.0.0\hostfxr.dll

```
