### ISSUE TITLE
Lots of CLR functions always end up on broken stacks

### ISSUE THREAD

**Issue by davkean** [microsoft/perfview#390]
I'm seeing lots of time spend in my traces of clr!COMString::IndexOfAny, clr!ProbablyContains and clr!InitializeProbabilisticMap. However, no matter how many times I record scenarios - usages of these methods almost always end up on a broken stack. I'm basically trying to find the caller to string.IndexOfAny - but to no avail.

Are there tips to figuring out why this is the case?

**Comment by vancem** [comment]
Can you point to a trace with the issue?    

If I had to guess, this issue is probably caused by the fact that this is a 32 bit process, and that relies on the C++ compiler generating call frames for methods.   The CLR is compiled in a what where some methods have been told to optimize the frame pointer away (a conscious choice was made to give up on stacks for clr!COMString::IndexOfAny because we wanted the perf more, the others were probably accidentally dragged in).   

If this is true, one possible work-around is to run the scenario as a 64 bit process (if possible).   This uses a very different way of crawling stacks that probably will work.   

Another work around is to set a breakpoint there in the debugger and do 'poor mans sampling' by simply observing the stacks that occur by hitting 'go' a bunch of times

**Comment by brianrob** [comment]
Requires a repro.  @davkean, if you have a repro of this, please re-open.
