### ISSUE TITLE
SysCallEnterTraceData + ProcessId and ThreadId not set

### ISSUE THREAD

**Issue by CaptainJackSparrow2** [Microsoft/perfview#391]
Hey all,

i'm not sure whether this is a real issue or not. Whenever i check the data within SysCallEnterTraceData, the given ProcessId as well as the ThreadId is -1. I saw several places in code where comments suggested, that there is/was an issue with the corresponding ProcessId and ThreadId.

Is there no ProcessId and ThreadId available in this case, or is there a bug? Unfortunately i haven't found anything in documentations concerning this topic.

Thx in advance <CaptainJack>

**Comment by vancem** [comment]
The SysCall events don't have any thread or process information which is why you see -1.   However IF there are stacks associated with the events the thread and process information is there and PerfView can extract it  (in my experiment it does get the thread ID.

It turns out that PerfVIew did this fixup for the threadID but not he process ID.   I have a fix in flight to fix it for the process ID as well.  

However you can work-around this problem by not using the EventViewer and instead us the 'Any Stacks' view for the SystCalls. these will have the process ID in them.

**Comment by vancem** [comment]
I have checked in the changes to make SysCalls work better.   I am closing the issue for now.
