### ISSUE TITLE
PerfView fails with a EntryPoint not found dialog box. 

### ISSUE THREAD

**Issue by SudhindraChegu** [Microsoft/perfview#449]
PerfView is a great tracing tool and it is very well documented.

We are trying to run the code of PerfView. but we are stuck with below mentioned error ::
"ReleaseSRWLockExclusive could not be located in the dynamic link library api-ms-win-core-synch-l1-2.dll"

![image](https://user-images.githubusercontent.com/34036727/33278435-8c66dc34-d3c1-11e7-9670-83606f42f1fb.png)

Setup Details are as below  ::
Visual Studio Community Edition 2017
.NET Framework 4.6.2
.NET Core SDK 2.0
Windows 7 64Bit

Please let us know if we are missing anything here

**Comment by vancem** [comment]
This kind of an error happens when you run native code compiled for Win10 on older OSes (You show you are trying to run this on Win7).

Are you by any chance running PerfView64.exe?  If so try just PerfView.exe (it should be fine).    The 64 bit versions of some of the native DLLs we use are compiled to run on older OSes (but the 32 bit versions should be).   I did not think we even had a 64 bit version of Win7...   

I will put an OS check into the 64 bit version to make this friendlier.

**Comment by SudhindraChegu** [comment]
Thanks for the quick response ... I got the above error after running Perfview 32Bit version. 

I got below error after running PerfView 64Bit version.
![image](https://user-images.githubusercontent.com/34036727/33302447-2a448ef0-d422-11e7-84e8-f470e5a64f0c.png)

How can we resolve this issue in PerfView 32/64Bit?

**Comment by bendono** [comment]
This looks similar to #355.

**Comment by vancem** [comment]
As noted in issue #355, that issue tracks this problem for 64 bit (and we are not fixing that).  This issue should only be for the 32 bit version (that is PerfView.exe NOT PerfView64.exe).

I don't have easy access to a Win7 machine at the moment.   Can someone tell me exactly when this dialog box appears?   I would expect it to NOT appear at startup, but rather when you try to actually collect.  Is that true?   (Since the issue indicated the tutorial).

I would also like to know the version number of the OS (what the 'ver' command returns).    From my reading of the code, if the OS version was 6.1 (which should be Win7), I would have expected even collection to work (for PerfView.exe).   

Finally one more thing you can try, is in the change your directory to 
```
%APPDATA%\PerfView\VER.*\x86\  
```
Where * is a date-like string (there should be only one such match).  Note the sizes of the 'KernelTraceControl*' files using a 'dir' command then overwrite one like this 
```
     copy KernelTraceControl.Win61.dll KernelTraceControl.dll
```
That will make PerfView use the Win7 version of this DLL, which should solve the problem (on Win7 systems it should have done this overwrite automatically).

Vance



%APPDATA%\

**Comment by SudhindraChegu** [comment]
@vancem : Thanks for the detailed response ...

As suggested, we will limit this issue to PerfView 32Bit Version only.

Scenario :::
1. Run Perfview from VS 2017 ( Build & Run)
2. Click 'Collect' Menu -> Click Collect option
3. Click 'Start Collection'
4. Error popup appears

Windows Version :::
Microsoft Windows [Version 6.1.7601]

Modifying KernelTraceControl :::
Tried copying the KernelTraceControl dll as suggested, but the issue still persists.

**Comment by vancem** [comment]
@SudhindraChegu  Thanks.   

Can you try two additional things:

*  copy the PerfView.exe from where it built (e.g. src\PerfView\bin\*\net45) to somewhere, and run it from there.   When you run things from the VS build directory, the default rules pick up dlls in a different way than when you run things stand-alone.   This problem is all about which DLL is being loaded.  

* Can you also see  if this repros using the PerfView.exe from the download center https://www.microsoft.com/en-us/download/details.aspx?id=28567

* If that does now work please open the PerFViewV1.8.zip file on 
https://1drv.ms/f/s!AmGrcRxfUGjQfI8wfZ0dD6Bv6Ps and try that.  

If any of these work, you have an effective work-around.    

As for a final solution, I am very surprised that copy the KerneTraceControl.win61.dll to KernelTraceControl.dll did not work (you probably need to try it again but don't launch PerfView from the build directory since it probably picked up the wrong version of KernelTraceControl.dll.

**Comment by SudhindraChegu** [comment]
@vancem :  It worked !! 
1st workaround gave way to the solution. Problem was with KernelTraceControl.dll.
Apparently, KernelTraceControl.dll downloaded from nuget package is not compatible with Win7 64Bit OS. After replacing it with "%APPDATA%\PerfView\VER.*\x86\KernelTraceControl.dll", this issue was fixed.

Thanks for all the help!!

**Comment by vancem** [comment]
@SudhindraChegu  this is good news (we now have work-around).     Your results are also consistent with my understanding of the issue.   As you have also figured out, KernelTraceControl.dll is the key issue here.  By default PerfView uses version of this DLL that only works on Win10.  However it ALSO keeps a second copy called KernelTraceControl.win61.dll, which it substitutes for the Win10 version on Win7.    

However it only does this in place where this DLL is normally loaded from (namely "%APPDATA%\PerfView\VER.*\x86), and ONLY for the 32 bit version (we don't have a 64 bit version that works on Win7 for this DLL).   

When you run PerfView from the debugger, however it turns out that default rules for loading DLLs kick in and the DLL that happens to be in the debuggers bin directory is used and NOT the fixed up one in "%APPDATA%\PerfView\VER.*\x86".    We have known for a while about the fact that when running PerfView from the bin location (which is what the debugger does), does pick up DLLs from a different location than when PerfView is normally run, but normally this difference does not matter (and only matters for a very limited number of people who actually build PerfView).    We have just tolerated this difference.  

Now if the explanation above is correct, the following SHOULD be true

* If you copy the PerfVew.exe out of the bin directory and run it, it should work properly even on Win7.
* Under the bin directory there should be both a KernelTraceControl.dll and a KernelTraceControl.Win61.dll.  If you the later on top of the former, then it should work even in the bin directory (that is debugging works, this is effectively what you did above).   

The important result of this however is the following

* This is only a problem for developers of PerfView not users of PerfView, and will only happen if you are developing on Win7 AND care about testing paths that collect data (that is when KernelTraceControl is used).   

This is likely enough of a corner case that it is not worth investing much to fix it (given I just gave a work-around).  Still if someone wants to suggest a SIMPLE (few line) fix, I am open to it.  

@SudhindraChegu  can you confirm that the behavior is what I outlined above (that PerfView 'just works' outside the bin directory and that copying KernelTraceControl.Win61.dll on top of KernelTraceControl.dll in the bin directory  fixes the issue in the 'run from bin' case.  .

**Comment by vancem** [comment]
This only affects devs running on Win7 and wanting to debug the ETW data collection part of PerfView, and there is a work-around (copying  KernelTraceControl.Win61.dll on top of KernelTraceControl.dll in your bin directory).  

This is a very small set (probably only SudhindraChegu), so the work-around is the solution and I am going to close the issue.

**Comment by SudhindraChegu** [comment]
Sorry for the delayed reply ...

@vance : Your analysis is right. Suggested workaround resolved the issue.
