### ISSUE TITLE
Expose jittedMethods.Count of TraceLog

### ISSUE THREAD

**Issue by Alois-xx** [Microsoft/perfview#476]
When doing realtime event processing the number of JITed methods can exceed 1 million methods if the tool is running for a longer time which then causes OOMs because the JIT events consume a significant amount of unmanaged memory. 
For 500 K events it is ca 1 GB of memory. To prevent OOMs it would be good to expose the count of JITed methods to be able to restart the trace session when an application specific threshold has been reached.

**Comment by vancem** [comment]
The problem with exposing just one method is that it does not really fix the problem (there are many things that the can make memory explode.     In fact this issue is what is trying Jeffs #482 (the idea is that you declare that you dont care about things further ago and some limit and then all things subscribing should try to trim their old stuff to keep memory under control.

Now Jeff's change is just a start (it provides a way of making a request) it does not actually insure that all existing state accumulators obey it.   

So you clearly do need something else in the mean time.    However there are a number of work-arounds

TraceLog.CodeAddresses.Methods.Count gives you a count of all the methods TraceLog is keeping track of.   It is a super-set of JITTed methods.   

EventLog has the 'Stats property that tells you about the count of every event that it has seen and that can be used to determine if it is time to restart (indeed you might look at a number of events).    In your case looking at the JIT event would do it.  

You can also simply subscribe to thinks like the JIT method to keep track of how 'big' things are getting.   

I am going to close this.  Please reopen it if you still believe the jittedMethods.Count is important to expose
