### ISSUE TITLE
ArgumentException When KernelEvents and InMemoryCircularBuffer Commands Are Used Together

### ISSUE THREAD

**Issue by shortspider** [Microsoft/perfview#525]
I am getting the following ArgumentException:

```
Exception Occurred: System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)
```

When I run this command:

`.\PerfView.exe collect -AcceptEULA -NoView -LogFile:log.txt -CircularMB:1000 -KernelEvents:Handle,Default -InMemoryCircularBuffer collection.etl`

However if I remove `-InMemoryCircularBuffer` everything works fine.

Contents of the log file:

```
PerfView logging started at 15-Jan-18 4:00:37 PM
[EXECUTING: PerfView collect -AcceptEULA -NoView -LogFile:log.txt -CircularMB:1000 -KernelEvents:Handle,Default -InMemoryCircularBuffer collection.etl]
Kernel keywords enabled: Handle, Default
Aborting tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
Insuring .NET Allocation profiler not installed.
Detected 64 bit system, removing 64 bit keys
[Exception Occurred: System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at PerfView.CommandProcessor.Start(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.Collect(CommandLineArgs parsedArgs)
   at PerfView.CommandProcessor.ExecuteCommand(CommandLineArgs parsedArgs)]
[DONE 16:00:37 FAIL: PerfView collect -AcceptEULA -NoView -LogFile:log.txt -CircularMB:1000 -KernelEvents:Handle,Default -InMemoryCircularBuffer collection.etl]
```

Any ideas? I am using Windows 10 and PerfView version 2.0.2.0.

**Comment by vancem** [comment]
I can repro your issue.   However I don't think I can do anything about it (but make a better error message (which I have done, but not yet checked in.  

The only work-around is the obvious one, don't use /InMemoryCircularBuffer Make /BufferSizeMB= bigger if you have lost events.

**Comment by shortspider** [comment]
@vancem what exactly is the relationship between BufferSizeMB and CircularMB? I started by setting CircularMB when I needed to collect for a long time (overnight sometimes waiting for an event to happen). However this ended up loosing events which is why I added InMemoryCircularBuffer (which is what the dialog that comes up when missing events are detected says to do). How does BufferSizeMB help?

**Comment by vancem** [comment]
CircularMB is the size the file on disk.  After reaching this size, you start overwriting the beginning of the file to create a 'window'.

BufferSizeMB is the size of a in-memory buffer used to hold events until they are written to disk.   You lose events when events fill up this buffer (because they are coming in faster than they can be flushed to disk).   

Perhaps counter-intuitively, even when BufferSizeMB > CircularMB you can still have lost events since the in memory buffer does not 'know' it is circular and thus throws away incoming events rather than trying to wrap.   

However in practice, if you make the BufferSizeMB large enough and stop the trace before that many events have been emitted, then you will not lose events.

/InMemoryCircularBuffer, teaches the system to use the in memory buffer to be circular and the dump it 'offline' at the end.   This guarantees not to lose events in the window that is collected, but as you can see, it is not supported in some cases.

**Comment by shortspider** [comment]
@vancem thank you so much for taking the time to explain all that, I really appreciate it.
