### ISSUE TITLE
does perfview works with .net core REST services

### ISSUE THREAD

**Issue by sajithajose** [Microsoft/perfview#556]
I am using visual studio 2015 for development of REST API services in .net core 1.0 
can I use perfview to profile my services?

is perfview running as standalone or can I use it along with visual studio?

my services are deployed in Linux machines in PCF (pivotal cloud foundry) . if remote profiling on PCF cloud is not supported, then I have to try profiling it within visual studio. 

please advise. 

Thank you

**Comment by vancem** [comment]
PerfView does not much care about what your service is, but it does care where it runs (because that affects how the data can be collected).  

Thus if you are trying to profiler your service on your VS 2015 development machine, then yes, you can use PerfView to do that.    However collecting on Linux (e.g. for production) then the capabilities are different (you can't collect with PerfView since it is a windows application, but there is a PerfCollect script that lets you collect CPU information (See the Help -> Viewing Linux Data for more).  

PerfView has no integration with Visual Studio.  It is stand alone.
