### ISSUE TITLE
EventRegister and NetCore

### ISSUE THREAD

**Issue by raffaeler** [Microsoft/perfview#558]
Not sure if this is the right place for EventRegister.exe.
After adding the nuget pacakge to the project references, the source generation fails because eventRegister doesn't know how to load nestandard types:
```
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
LoaderException:
System.TypeLoadException: Could not load type 'System.Object' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' because the parent does not exist.
```

In other words, I am trying to create a custom event source from a netcore app, and I can't find a smooth way to do it.
Hints?

**Comment by vancem** [comment]
The Microsoft.Diagnostics.Tracing.EventRegister  nor the Microsoft.Diagnostics.Tracing.EventSource package should be used on .NET Core.   

EventSource is built into the .NET Framework (System.Diagnostics.Tracing.EventSource), and you should be using that.    

What makes you feel like you need these things?  (what is your scenario?)

**Comment by raffaeler** [comment]
I need to use the evenregister in two different project/use-cases:
1. A .NET 4.6.2 project using netstandard libraries. As soon as any netstandard library is added to the references, a dependency on the System.Runtime and other dlls is required.
In the specific case, the dll declaring the event source is .net 4.6.2 but it has a dependency on a netstandard dll declaring a bunch of interfaces. As a consequence, eventregister.exe need to load the System.Runtime.dll.
I could fix that but it is extremely hard because the eventregister.exe enforce loading a specific version, preventing newer System.Runtime.dll to be loaded. I mean newer than those declared in the dll manifest.
Normally I should just add a bindingRedirect, but this is not possible because the eventregister is inside a nuget package.

2. An ASP.NET Core running on Windows with CoreClr as a runtime.
How can I declare a custom eventsource? All the docs explain how to use the standard event sources but not a custom one.

Thank  you

**Comment by vancem** [comment]
@raffaeler  I am confused by your response.  

First, EventRegister is a tool that is used at build time (or maybe install time), but it is not used at all at runtime.   What I am *guessing* you are saying is that you are using the https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource/ package which uses the 
https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventRegister/ package to install build-time checking of our EventSource.     This is actually completely optional, the package https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/ is basically the code that runs at compile WITHOUT the extra help at build time.  It works fine.   Thus if you just used that you would avoid any issues with EventRegister.

However **WE GERALLY DON'T WANT PEOPLE TO USE Microsoft.Diagnostics.Tracing.EventSource/**.   Its sole purpose was to allow users to get 'up to date' versions of EventSource without having to update their .NET Runtime.   However this value has frankly gone away.   As you can see the nuggt package has not been updated since 12/2015, but V4.6.2 of the runtime was release  8/16, and probably contains most if not all the changes.  Thus there should be no reason to use this package.   

You describe some issues using NetSTandard, but they don't seem to be particularly related to EventSource (how does using Microsoft.Diagnostics.Tracing.EventSource possibly help?)   Now your scenario (using .NET Standard on V4.6.2 is something we want to work so we should figure out exactly what it is not working for you, but that does not seem to be particularly related to EventSource 

> An ASP.NET Core running on Windows with CoreClr as a runtime.
> How can I declare a custom eventsource? All the docs explain how to use the standard event sources but not a custom one.

Certainly Sytem.Diagnostics.Tracing.EventSource exists on .NET Core (it is after all part of .NET Standard).   

I don't really understand you question about a custom EventSource.  You declare it the same way you do for on the Desktop  For example [This blog](https://blogs.msdn.microsoft.com/vancem/2012/07/09/introduction-tutorial-logging-etw-events-in-c-system-diagnostics-tracing-eventsource/) talks about the very basics.   It has not changed.

**Comment by raffaeler** [comment]
Thank you for the answer.
The first issue is simply related to the eventregister.exe that, being launched via nuget or manually, has problems in loading the dlls having dependencies on netstandard.
I will talk with the other guys who went into this direction and discuss with them if we can change the way the create and register the provider.

With regards to the second issue I am not sure if I understood your answer. My point is to register a custom provider on netcore. Again, I will re-read the article to see if I missed something and let you know.

**Comment by vancem** [comment]
I am closing this issue.   

The main point here however, is that for .NET Core, you should NOT need the Microsoft.Diagnostics.Tracing.*  packages at all.   If you are using them, you don't need to.  Simply use System.Diagnostics.Tracing.EventSource (which is part of NetStandard), and life is good.

**Comment by blumu** [comment]
@vancem I work on a project that relies on `Microsoft.Diagnostics.Tracing.Register` (and `eventRegister.exe`) to generate custom ETW manifest files. We massage the generated manifest files in a non-trivial way (e.g. adding a subscription to implement ETW forwarding with `ForwardedEvents`) so just relying on `System.Diagnotics.Tracing` does not cut it.
Since the package/tool `Microsoft.Diagnostics.Tracing.Register` does not work on netstandard, what's the supported equivalent?

**Comment by vancem** [comment]
@blumu - I don't really understand your scenario yet.    I don't recognize the namespace Microsoft.Diagnostics.Tracing.Register.    I assume you mean Microsoft.Diagnostics.Tracing.EventRegister. which is just a nuget package that contains EventRegister.exe.     

Note that the full source code for EventRegister is in the PerfView repository at https://github.com/Microsoft/perfview/tree/master/src/related/EventRegister.   

However it would be my expectation that you would not need this source code (and frankly usome of its functionality uses native components that are windows specific).    

As a rule, if you care about manifests (that is you expect to register them), you are windows specific (what would you do with a ETW manifest on Linux?)      Under such conditions building on windows is typically what you would be doing, and thus so you can use the stock EventRegister if you need it. 

Note that the bulk of what EventRegister does that is cross platform is actually done by the EventSource.GenerateManifest (which is part of EventSource (that is it coms with the .NET Framework, and does work cross platform).   EventRegister is simply a 'host' that lets you call that API (and save it to a file).   The rest of what EventRegister does (actually registering a manifest) is something that only can be done on Windows.   

If you believe I am not addressing your issue, you will need to describe what your situation is in more detail.

**Comment by blumu** [comment]
@vancem Yes I meant `Microsoft.Diagnostics.Tracing.EventRegister`. To clarify our scenario: we generate the manifest at build time from the assemblies containing the EventSource types. We then transform it into a new manifest. This adds specific configuration to the manifest to enable forwarding of ETW events (a Windows-specific feature). We then use `wevtutil` to register the manifest on Windows.
Our project containing the EventSource types abstracts our service \telemetry: on Windows it's implemented using ETW, on Linux we use something else.  The project currently targets net462 which was fine so far because we used Mono, but we are now migrating from Mono to dotnet core, we thus need to target netstandard20.

- I understand that we could call `eventregister.exe` ourselves to make it work, instead of relaying on EventRegister to generate it at build time. Though that would require us creating a separate net462 project just to download the eventregister.exe dependency.
- I will take a look at netstandard's `EventSource.GenerateManifest`, though from what I can see it only generates the manifest file itself (the equivalent of `*.etwManifest.man`) and not the corresponding assemblies (`*.etwManifest.dll`). I have to give it a try but I wonder if the assembly would be needed by `wevutil` in which case we'd need to find out how to generate the *.etwManifest.dll assemblies.

**Comment by vancem** [comment]
Yes EventSource.GenerateManifest just generates the *.man file.   To generate the DLL EventRegister needs to call the MC.exe program (a binary that it carries) to convert it to a binary resource, and then uses the C# compiler to make a DLL with that binary resource in it.    The code that does this is in  https://github.com/Microsoft/perfview/blob/master/src/related/EventRegister/Program.cs and is pretty straightfoward.   

Logistically, EventRegister does nothing that would not run if the project was netstandard2.0.   Ultimately all you care is that you run the tool on your code and it produces a DLL that you want (that ultimatel;y runs on Windows)     

At worst, you are free to clone the EventRegister code yourself and make building it part of your build and you use the resulting tool to generate what you need.     

From our end, generating ANY version of the EventRegister package will require some work that we are not likley to prioritize highly for the forseeable future,   Thus I am looking for ways that you can unblock yourself without us having to do that.

**Comment by blumu** [comment]
Thanks for the pointers @vancem So I had to build the DLL resource assembly for `wevtutil` to work. Here is the F# code for reference in case anyone else needs it. CC: @raffaeler
```fs
/// Generate the ETW manifest files (.man and .dll) for a given EventSource type.
/// By William Blum, Jan 15 2019.
//
// Prerequisite:
///  Download winmeta.xml from https://raw.githubusercontent.com/Microsoft/perfview/master/src/related/EventRegister/winmeta.xml
///  Update the INPUT section below to point to your ETW EventSource type
#r @"netstandard.dll"
#r @"System.Diagnostics.Tracing.dll"
#r @"FSharp.Core.dll"
#r @"Microsoft.FSharpLu.dll" // Requires Microsoft.FSharpLu nuget

open System.Diagnostics.Tracing
open System.Xml.Linq
open System.Linq
open System.IO
open Microsoft.FSharpLu
open Microsoft.FSharpLu.File
open Microsoft.FSharpLu.Logging
open Microsoft.FSharpLu.Diagnostics

//// Input
#r @"MyEventSource.Dll"
let EventSourceType = typeof<MyEtwEventSourceType>
let ManifestFilePrefix = "MyEventSourceId"
let OutputDirectory = __SOURCE_DIRECTORY__
///

// Tools path
let WinmetaXml = __SOURCE_DIRECTORY__ ++ "winmeta.xml" // File needs to be downloaded from https://raw.githubusercontent.com/Microsoft/perfview/master/src/related/EventRegister/winmeta.xml
let pfx86 = System.Environment.GetEnvironmentVariable("ProgramFiles(x86)")
let mc = pfx86 ++ @"Windows Kits\10\bin\x64\mc.exe"
let rc = pfx86 ++ @"Windows Kits\10\bin\x64\rc.exe"

/// Compile an XML ETW manifest file into a resource assembly
/// Logic borrowed from https://github.com/Microsoft/perfview/blob/4570e21b27378c2cec5a35756240d5672c1306a0/src/related/EventRegister/Program.cs#L529
/// as suggested by perfview maintainers since they have no intention of porting this to netstandard: https://github.com/Microsoft/perfview/issues/558
let compileManifest (manifestXmlPath:string) (manifestDllPath:string) =
    async {
        let outputDirectory = System.IO.Path.GetDirectoryName(manifestXmlPath)

        // put runtime directory on the path to access the CSC compiler
        let runtimeDir = System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory()
        let pathVariable = System.Environment.GetEnvironmentVariable("PATH")
        if not <| pathVariable.Contains(runtimeDir) then
            System.Environment.SetEnvironmentVariable("PATH", runtimeDir + ";" + pathVariable)

        // Compile Xml manifest into a binary reasource, this produces a
        //     * MANIFEST.rc               A text description of the resource which refers to
        //     * MANIFESTTEMP.Bin          The binary form of the manifest
        //     * MANIFEST_MSG00001.Bin     The localized strings from the manifest
        printfn "Compiling Manifest %s to ETW binary form." manifestXmlPath
        let! mcExitCode = Process.startProcessAsyncAndWait mc (sprintf "-W \"%s\" -b \"%s\"" WinmetaXml manifestXmlPath) outputDirectory Microsoft.FSharpLu.Diagnostics.Process.ProcessStartFlags.Elevated
        if mcExitCode <> 0 then
            Trace.failwith "mc compilation failed: %d" mcExitCode

        let rcFilePath = Path.ChangeExtension(manifestXmlPath, ".rc")
        let resFilePath = Path.ChangeExtension(manifestXmlPath, ".res")
        let csFilePath = Path.ChangeExtension(manifestXmlPath, ".cs")

        // Compile the .rc file into a .res file (which is the binary form of everything in the
        // .rc file
        let! rcExitCode = Process.startProcessAsyncAndWait rc (sprintf "\"%s\"" rcFilePath) outputDirectory Microsoft.FSharpLu.Diagnostics.Process.ProcessStartFlags.Elevated
        if rcExitCode <> 0 then
            Trace.failwith "rc compilation failed: %d" rcExitCode

        // At this point we have .RES file, we now create a etw manifest dll to hold it a
        printfn "Creating Manifest DLL to hold binary Manifest at %s" manifestDllPath
        File.Delete(manifestDllPath)
        // Make a dummy c# file
        File.WriteAllText(csFilePath, "")
        let! rcExitCode = Process.startProcessAsyncAndWait
                            "csc.exe"
                            (sprintf "/nologo /target:library \"/out:%s\" \"/win32res:%s\" \"%s\"" manifestDllPath resFilePath csFilePath)
                            outputDirectory
                            Microsoft.FSharpLu.Diagnostics.Process.ProcessStartFlags.Elevated
        if rcExitCode <> 0 then
            Trace.failwith "csc compilation failed: %d" rcExitCode
    }

/// Generate the ETW manifest file from the EventSource type and compile it into a resource assembly
let generateAndCompileManifest sourceId eventSourceType =
    async {
        let manifestFilePath = OutputDirectory + (MyEventSourceId + ".etwManifest.man")
        let resourceAssemblyFile = OutputDirectory + (MyEventSourceId + ".etwManifest.dll")
        let manifest = EventSource.GenerateManifest(
                            eventSourceType,
                            resourceAssemblyFile,
                            EventManifestOptions.None)
        System.IO.File.WriteAllText(manifestFilePath, manifest)
        do! compileManifest manifestFilePath resourceAssemblyFile
    }

generateAndCompileManifest EventSourceType |> Async.RunSynchronously
```

**Comment by jeffreywstevens** [comment]
I evaluated this tech years ago and really liked the ability to get Eventsource ETW events into the Application and Service logs and using Event Viewer.  The ability to enable/disable is nice too.

A misbehaving app was inspected with Perfview and its logging was not ETW.  A much slower medium.  We want to change that.  However, we also want to inspect the same events with Splunk and / or Elasticsearch.  Both can ingest Application and Service log events apparently. 

@blumu my F# is rusty.  I really wish this was c#.  Did you write the F# from eventregister c# code from @vancem.   Does the F# compile to an EXE with parameters or need code changes?





So getting Eventsources into Applications and Service Logs on Windows does have some benefit
