### ISSUE TITLE
CPU Sampling Rate Is Not Taken Into Account For ms CPU Time Calcuation

### ISSUE THREAD

**Issue by Alois-xx** [microsoft/perfview#570]
When looking at CPU Sampling data I have noticed that the ms time are equal to the profiling event counts. This is not true if the data was taken with a different CPU sampling rate. 
This confuses users who use WPA and compare the results. The relative times are ok.

**Comment by brianrob** [comment]
@Alois-xx, you are correct.  The stack viewer will display counts of events rather than ms of CPU.  This is designed to essentially be generic so that there is no assumption as to the units other than "event count".

It could be made to be more specific for some views such as CPU, but this has not been done as of yet.
