### ISSUE TITLE
Update TraceEvent et al to build against netstandard2.0

### ISSUE THREAD

**Issue by jazzdelightsme** [Microsoft/perfview#611]
It currently builds against netstandard1.6. Upgrading to netstandard2.0 (which has been out for a while now) opens up a *much* larger API set to build against. Unfortunately, it doesn't seem like a trivial change (it looks like the OSExtensions package needs to get rebuilt).

**Comment by xiaomi7732** [comment]
@jazzdelightsme it is very interesting you filed this. I filed #608 as well yesterday.

**Comment by jazzdelightsme** [comment]
Oh man... I had started typing mine before yours was filed, but got interrupted and didn't submit until this morning. D'oh! This one can be closed.

**Comment by vancem** [comment]
Just to be clear, the value of having a netstandard2.0 version is only useful for implementers IN TRACEEVENT (clients should not care).     Moreover we will need to support netstandard 1.6 for a while at least, which means, if you want to submit to the public repository, you need to continue to support the V1.6 netstandard (maybe by using NETSTANDARD1_6 define.

I have an update to directly support Netstandard2.0, but that is mostly because I don't want the limitations of netstandard 1.6 (because we have some #if NETSTANDARD1_6 that turn off functionality) to affect .NET Core users.

**Comment by xiaomi7732** [comment]
@vancem 
I agree that to enable .NetStandard 2.0 is useful for implementations in TraceEvent.
However, I won't say it is totally the client doesn't care about it.
We might provide some new features in TraceEvent where uses the new API. .NET Core 2.0 app will be able to use these APIs while .Core 1.0 client won't be able to.

I think we shall agree on some simple principles like:
1. TraceEvent shall multi-targeting FullFx, netstandard1.6 & netstandard2.0.
2. Any new features use API in 2.0 shall be in precompile section of NETSTANDARD2_0 and thus will only available for .NETCore 2.0 app. Netstandard1.6 shall either not expose these APIs or log a warning for not able to implement the function because of lack of API support.
Ideas? Thoughts?

**Comment by vancem** [comment]
PR #612 addresses this Shortly Version 2.0.10 of the Nuget package will have a 2.0 target.    The 2.0 target should have all features, but the 1.6 target does fail or degrade in some cases (because it lacks access to some feature it needs).   We expect the 1.6 target to mostly be used for simple collection and simple processing (e.g. when part of a test harness that is testing old code).   Mostly we care about the 2.0 version
