### ISSUE TITLE
.NET Calls - How do I analyze it?

### ISSUE THREAD

**Issue by fujiy** [Microsoft/perfview#646]
After collecting a trace with .NET Calls checkbox enabled, where do I see the results?

I found these events, but I can't see how it would help:

![image](https://user-images.githubusercontent.com/1336227/39306729-4f73b3ec-4937-11e8-93cc-e359dfb382ab.png)

Is it meant to work as a instrumentation profiler?

**Comment by mattwarren** [comment]
There's some helpful videos on Channel 9, see [here](https://channel9.msdn.com/Series/PerfView-Tutorial) and [here](https://channel9.msdn.com/Shows/Defrag-Tools?term=PerfView). In particular [PerfView Tutorial 2 - A Simple CPU Performance Investigation](https://channel9.msdn.com/Series/PerfView-Tutorial/PerfView-Tutorial-2-A-Simple-CPU-Performance-Investigation) should help with your scenario

**Comment by fujiy** [comment]
@mattwarren, I watched the videos, but I would like to understand how ".NET Calls" can help me to do a more detailed analysis.

**Comment by vancem** [comment]
The calls in .NET Calls show up in the 'Any Stacks' view in the 'Advanced Group' view.   My suggestion is to select that 'EnterCall' node -> right click -> Include Item, which filters out all other events from the view.

You can then see all the calls.  You are just seeing call counts.   Generally speaking you don't want to start you investigation here.  It is mostly useful for cases where you are really trying to understand HOW your program works (whether caching is working etc).   Call counts are a poor approximation for time (which is what you usually care about), which is why looking at the CPU time view is typically more interesting.   

Call Counts can be useful however, to really understand in details WHAT your code is doing (rather than how long it takes).

**Comment by fujiy** [comment]
Thanks @vancem
