### ISSUE TITLE
Remove ASP.NET Events (and URLs) from a collection

### ISSUE THREAD

**Issue by MarcinJuraszek** [Microsoft/perfview#649]
I'm trying to get PerfView to perform a regular collection with some CPU, Memory and GC tracing but because of compliance/privacy requirements I don't want the ASP.NET Events to be captured during collection as they contain the URLs for requests served by the machine during collection.

I'm using the CLI. Here's what I have so far:

> PerfView.exe collect -CircularMB:3072 -StackCompression -MaxCollectSec:60  -Merge:True -Zip:True -RundownTimeout:600 -MinRundownTime:120  -DotNetAllocSampled -AcceptEULA

This works fine but when I open "All events" data I can see `Microsoft-Windows-ASP.NET/Request/Start` which contains the URLs I don't want to be part of the trace.

Event Name | Time MSec | Process Name | Rest
-- | -- | -- | --
Microsoft-Windows-ASPNET/Request/Start | 53,634.318 | w3wp (6040) | HasStack="True" ThreadID="13,264" ProcessorNumber="0" HttpVerb="GET" FullUrl="http://marcinj-dev9:80/test.aspx" RequestCorrelationId="00000000-0000-0000-0000-000000000000" ActivityID="e33fe594-38b9-4bbf-8748-fff5daa45c01"

Is there a way for me to disable these particular events? There is *Additional Providers* functionality, how do I get a reverse of that, something like *Removed Providers*?

**Comment by vancem** [comment]
In general you can turn off automatically added providers by setting their keywords and level to 0.   If you look in the log you will see all the providers that PerfView turns on.    There are actually two different providers for ASP.NET so you may need to turn them both off.  

Thus if you use

PerfView /Providers:ASP.NET:0:0,Microsoft-Windows-ASPNET:0:0 collect

You should get what you want.   

Note that all the 'extra' providers are keyed to the use of the default CLR events.  Thus if you restrict your CLR events, then PerfView does not try to turn on anything else.   You don't want to turn off all CLR events because you can't decode .NET STacks properly, but the 'JitSymbols' set of CLR events are the minimum needed (you may also wish to turn on the GC CLR events).   Thus 

PerfView /ClrEvents=JitSymbols collect

Will collect the default kernel events (The CPU and Disk stuff), and just enough CLR events to decode stacks (and no other providers).     You can turn off some Kernel events as well (but you need to keep Process,Thread,ImageLoad and Profile events to decode CPU stacks.    Thus

PerfView /ClrEvents=JitSymbols /KernelEvents=Process+Thread+ImageLoad+Profile collect

Is the minimum for decoding CPU profile of .NET processes. 


P.S: Merge and Zip are on by default so you don't need to specify them.
