### ISSUE TITLE
Presets: better handling of process filter via IncPats

### ISSUE THREAD

**Issue by ilabutin** [Microsoft/perfview#656]
After #446 was implemented I realized that I was using it to troubleshoot the same process all the time, so was not experiencing issues with IncPats field.
PerfView uses it to filter stacks by process, which means that it's kind of difficult to use presets across processes - IncPats is replaced by another process name and thus stacks are not showing what is expected.

I guess there are two scenarios for preset usage:
1. Share them together with .ETL file. Here all fields are relevant.
2. Use them as quick way to set favorite grouping/folding/Inc/Exc patterns. In this case process name as IncPat does not fit well.

@vancem  What do you think? Am I overcomplicating things? Or should we make clever logic to exclude "Process %..." part from IncPat when saving presets?

**Comment by vancem** [comment]
What we did before presets (for the default values), was to only support Group Pat, Fold Pat, and Fold %.   

The simple thing to do is to simply not support Inc/Exc patterns.   

If you don't like that, the real issue is whether 'applying' means merge or replace.  

One resolution each part of the preset, have a 'merge' checkbox.   This determines if the value should be merged when the preset is applied (merging for Fold% can be max).   The 'Save as Preset' only does NOT capture inc/exc.  For those, you have to go to the 'Manage' dialog and fill them in manually (you can make faster way if you like).
