### ISSUE TITLE
Update KernelTraceEvent parser

### ISSUE THREAD

**Issue by rovarma** [Microsoft/perfview#677]
With the Windows 10 Creators Update, a new function has been added to the Windows API to set the name of a thread ([SetThreadDescription](https://msdn.microsoft.com/en-us/library/windows/desktop/mt774976(v=vs.85).aspx)). To support this API, a new event `ThreadSetName` has been added and a new field `ThreadName` has been added to `Thread_TypeGroup1` (from version 4 and up). This allows tools built on top of ETW to display thread names, which was not possible with the old `RaiseException` method of setting a thread name.

WPA supports displaying the thread name as follows, which is very convenient:
![image](https://user-images.githubusercontent.com/8319699/40020773-39bddefc-57c3-11e8-9d17-3dd01d5400ca.png)

It would be nice if TraceEvent/PerfView could also support this. This seems to require an update to a file that the KernelTraceEventParser is [generated from](https://github.com/Microsoft/perfview/blob/master/src/TraceEvent/Parsers/kerneltraceeventparser.mof). However, that file was last updated two years ago and according to the comments comes straight out of the Windows source tree.

Is there any chance of seeing an update to TraceEvent/KernelTraceEventParser to support the new thread names?

Thanks!

**Comment by vancem** [comment]
It is reasonably straightforward to add the support you describe, however I tried to generate this new information.  I was on  the April 2018 update of Win 10 (build 17134), and I used \system32\wpr.exe to collect a trace and looked at the 'Thread/Start' events but they are all version 3 (not version 4).

**Comment by rovarma** [comment]
Yes, I noticed that as well. 

However, even if those events are being advertised as version 3 in the header, if you look at the user data blob in a debugger, you'll notice that the new version 4 field data *is* there. And WPA can display the new data just fine.

It seems some magic is happening somewhere, but I haven't been able to determine what it is yet. Perhaps WPA has some special case handling for this event?

**Comment by vancem** [comment]
Can you tell me an application (hopefully in the OS), that I can run that uses the Thread naming feature?  I don't actually see this extra information in any of the ThreadStart events that I have in my WPR trace.  (I am dumping the bytes and there are no strings in there).    Perhaps it only adds it if it is non-empty.   

WPA is probably using the length of the payload to determine if the field is present or not.   I do something like that for some events.    But first I have to see events with the information!

**Comment by rovarma** [comment]
Hey,

I'm not aware of any applications in the OS that use the new API, but I do know that recent versions of Chrome use it:

![image](https://user-images.githubusercontent.com/8319699/40563479-2cb29f4a-6065-11e8-831e-45d3fa471134.png)

For myself, I used a tiny test app to experiment:

```
#include <thread>
#include "windows.h"

int main()
{
	std::thread thread([]()
	{
		SetThreadDescription(GetCurrentThread(), L"Test Thread Name");

		while (true)
		{
		}
	});
	thread.join();
        return 0; 
}
```

Running this code, then starting a trace (or starting a trace before starting the app) should result in the thread name being shown in WPA:

![image](https://user-images.githubusercontent.com/8319699/40563562-7d06c3fe-6065-11e8-8c01-528af5e418eb.png)

**Comment by vancem** [comment]
OK that is helpful.   I have figured out what is actually happening.    As you point out they did not bump the version number.   What is also true is that most commonly Thread/Start will NOT have a name (typically threads are given a name after they have started).    However Thread/Stop DOES.  

In addition there is a Thread/SetName event which basically happens when the API is called.    This event needs 'help' as like several other Kernel events it does not set the ThreadID in the usual way (TraceEvent has a bunch of logic to fix this.

Anyway, I understand how to make this work.   Maybe I will do it over the weekend (no promises however).    I think I may modify .NET Core to annotate its threads (which would be nice).

**Comment by rovarma** [comment]
OK, thanks for the info. So if I understand correctly, the way to deal with the new data is to check if the user data length > whatever the version 3 size was? It's kind of odd that they didn't bump the version number, since changes like this seem like what the versioning system was intended for. Any ideas why they didn't?

**Comment by vancem** [comment]
Previously you check the version number to see if a field is present.   They probably did NOT bump the number because it breaks existing code (which probably has a == comparison rather than a <= comparison).  

I think the have probably moved to a new guideline.  Basically you never bump version numbers, but instead add things to the end.   Fields after the first version should simply check if the length shows that the field is there.   This is as quick as a very check and robust.

**Comment by rovarma** [comment]
Alright. Thanks for adding the support! I notice that you didn't update the kernel MOF file. Is this because you added the support by hand?

**Comment by vancem** [comment]
Yes, I added the support by hand.   The kernel events have so much special case support, that the MOF file was only used the first time to have something to start with.
