### ISSUE TITLE
Error: exception while opening CTF (lttng) data.

### ISSUE THREAD

**Issue by GunSharp** [microsoft/perfview#734]
Hello,

I'm pretty new to profiling and thus I followed the instructions on https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md
I managed to collect data (sampleTrace.trace.zip) of my application. However as soon as I open the file with PerfView, it gives an error and only show the CPU-Stacks.
Am I doing something wrong or is this a bug?
Thank you in advance for your response.

(data and log-file attached).
[sampleTrace.trace.zip](https://github.com/Microsoft/perfview/files/2345359/sampleTrace.trace.zip)
[Status.txt](https://github.com/Microsoft/perfview/files/2345360/Status.txt)

**Comment by JamesDunne** [comment]
I've encountered the same error. It was working fine before I copied in the `crossgen` tool but fails afterwards.

**Comment by brianrob** [comment]
@GunSharp apologies for the very long delay in responding to this.  I opened your trace file and it looks like the error you got is expected, because there is an LTTng trace present in the file but it contains no events.  The error is essentially ignorable, and won't affect your ability to open the CPU stacks data.  I was able to open and view your trace.

If you do continue to run into issues, please let me know.
