### ISSUE TITLE
EventRegister.exe loads assembly without following assembly redirects

### ISSUE THREAD

**Issue by wasker** [Microsoft/perfview#741]
Consider project A (.exe) depending on project B (.dll); project B consumes package C, which brings EventRegister build targets. Both projects A and B are on
.NET Core 1.0.0 (all versions are matching). If project A is upgraded to .NET
Core 1.1.x, while project B isn't, EventRegister.exe will produce
LoaderException, until project B is moved to the same version of .NET Core.

> Error MSB3073
> The command ""C:\.nuget\packages\microsoft.diagnostics.tracing.eventregister\1.1.28\build\eventRegister.exe" -DumpRegDlls @"D:\work\Debug\ux.eventRegister.rsp" "D:\work\Debug\ux.exe" " exited with code 1.
> 

It looks like the code attempted to have .exe.config to be loaded into the app
domain, but the line is commented out.

I suggest revisiting that decision, or maybe roll some kind of custom reflection
using app domain events.

**Comment by vancem** [comment]
Loading other people's DLLs is hell.   Basically they can have an arbitrary chain of dependencies that frankly are in the limit unknowable.  

Logically, EventRegister wants to do is to treat the IL file like it was data and reflect over it WITHOUT RESOLVING ANY DEPENDENCIES.    

There are now tools/libraries that do this (e.g. CCI, ...).   Ideally EventRegster uses one of these.  

This would get us out of that hell.    It is not clear however, it worth the effort (if someone wants to do that great, but we have not had a request for over 2 years. 

Note that there is a work-around for any particular client.   Simply place your EventsSource in a DLL with SIMPLE dependencies (that is it is built with just built in things).   This is always possible since EventSource is PUBLISHING and API, and only USES EventSource tiself in its implementation. 

Such a DLL will NEVER cause grief with EventRegister (since it can be loaded 'anywhere'.   It however can be USED from any application with any kind of loader behavior).

**Comment by wasker** [comment]
Thanks for detailed comment!

The issue with our situation is that our EXE has to directly consume the package (e.g. "X"), which brings EventRegister dependency in. That is, unless ProjectReference style projects would allow us to consume package "X" indirectly via the intermediate "pure DLL", which would take a hit of EventRegister, like you suggest. I'll investigate this.

Do you happen to know the story about [this line in Program.cs](https://github.com/Microsoft/perfview/blob/f2f96b2785c37270daeef22295e9aedab24db2d1/src/related/EventRegister/Program.cs#L164)? I assume there're some good reasons for it to be commented out. Although, I'd expect framework to provide this kind of facility for consumers of reflection APIs...

**Comment by vancem** [comment]
> Do you happen to know the story about this line in Program.cs?

I did not write the funky loading code in EventRegister.   The developer who did is not longer in the group, and wrote it several-to-many years ago so even he may not remember.     

Ideally you could get the library package to not take a dependency on EventSource but EventSource.Redist.

**Comment by wasker** [comment]
Fair enough. Thanks for your time!
