### ISSUE TITLE
EventRegister build targets do not allow opt-out

### ISSUE THREAD

**Issue by wasker** [Microsoft/perfview#742]
Our project consumes another library, which brings EventRegister package in. We
do not use EventRegister, however, we cannot opt out from running it during the
build. Due to issue like this (#741), it causes us to constantly keep all
dependency versions in sync, which shouldn't be the case in .NET world.

Unfortunately, we cannot opt-out from consuming build targets altogether using
CSPROJ instructions, because there're other tasks that should be run.

I suggest adding a way to opt-out from running EventRegister, if its targets
were included in the build.

**Comment by vancem** [comment]
You can ask your library provider to 
1.Ideally skip Microsoft.Diagnostics.TrackingEventSource completely and simply use the built in System.Diagnostics.Tracing.EventSource.
2. If they need things to work on old .NET Runtimes, then they should use Microsoft.Diagnostics.TrackingEventSource.Redist, which skips the EvenRegister build time rule.   

Note that I am not averse to adding a bit of logic to the *.targets file to provide an opt-out.    It is just that it will take work to get to the point where we can build / sign the package, and it is not clear what the priority is.   

Also I note that the current *.targets file can probably be neutered by overriding AssmName to be a dummy file that is guarenteed to work.   I realize this is a hack, which is why the above two options are better, but I throw it out there as an idea.

**Comment by wasker** [comment]
Vance, thank you very much for pointing me to Microsoft.Diagnostics.Tracing.EventSource.Redist! It turns out, we can use it in our case, which completely solves the problem.
