### ISSUE TITLE
INVALID_HANDLE_VALUE constants has wrong value

### ISSUE THREAD

**Issue by RubenHesselbaek** [Microsoft/perfview#766]
The INVALID_HANDLE_VALUE constants has the value -1, which means INVALID_HANDLE_VALUE, but according to the documentation on https://docs.microsoft.com/en-us/windows/desktop/etw/starttrace
It's mention that invalid handles have the value 0.
This among other thing leads to closing+ reopening realtime session, when all you want is to attach and most likely other stuff where the session is deemed invalid, but is not.

**Comment by vancem** [comment]
I have fixed it so that after calling StartTrace we insure that on failure the handle is INVALID_HANDLE_VALUE.    That brings the StartTrace API in line with the expecations of the higher level code.

If StartTrace returns INVALID_HANDLE_VALUE (that is -1), to represent a valid trace, then we would still have problems, but I don't think this is the case.   

I am closing this issue, feel free to reopen it if you feel there is still something to fix.
