### ISSUE TITLE
Limit of concurrent TraceEventSessions?

### ISSUE THREAD

**Issue by szehetner** [Microsoft/perfview#769]
If I try to create more than 8 concurrent TraceEventSessions on one machine, I get the Exception "Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA)". It doesn't matter if they are created within one process or in multiple processes.

Where does this limit come from and can it be increased?

I found that Windows 10 has a limit of 64 concurrent ETW Sessions (https://docs.microsoft.com/en-us/windows/desktop/etw/event-tracing-sessions), but there are only ~20 sessions active on my machine. There is also a limit of 8 concurrent SystemTrace sessions (https://docs.microsoft.com/en-us/windows/desktop/etw/configuring-and-starting-a-systemtraceprovider-session) and also 8 concurrent private logger sessions (https://docs.microsoft.com/en-us/windows/desktop/etw/configuring-and-starting-a-private-logger-session), but as far as I can see a TraceEventSession does not create any of those.

Code to reproduce this:
```csharp
var sessions = new List<TraceEventSession>();
try
{
    for (int i = 0; i < 10; i++)
    {
        var session = new TraceEventSession("SessionTest_" + i);
        sessions.Add(session);
        session.EnableProvider("abc"); // throws for the 9th session
    }
}
finally
{
    foreach (var session in sessions)
        session.Dispose();
}
```

**Comment by vancem** [comment]
This is not an limitation in TraceEvent.  It is some limitation in the OS but I don't have details.   I will see if I can find out more.

**Comment by vancem** [comment]
I suspect that there is a limit has to do with the fact that the session is a real time (not file based), but at this point it is only a guess (you can try changing it to create file-based sessions).

**Comment by szehetner** [comment]
I tried, but I get the same error with file-based sessions.

**Comment by vancem** [comment]
Two other things to try, is to use a real Manifest-based provider.  I would recommend Microsoft-Windows-PowerShell.     Second, try using Microsoft-Windows-PowerShell for the first 5 providers then switch to Microsoft-Windows-ReadyBoost, and see if you get more than 8.   What I am trying to discover is if it is the number of sessions or the number of sessions per provider that is limited.

**Comment by vancem** [comment]
I heard back from a query I made to ETW experts and the said

> Yes, each individual provider can only be enabled to 8 sessions at a time. 

You should confirm this by doing the experiment I mentioned above (enabling differnet providers on the differnet sessions and see if that allows you to create more sessions.

I don't have alot of personal experience with it, but you CAN share sessions (attach to existing sessions).   It means that the set of events being selected has to be uniform, but otherwise it should work.  That may be a useful work-around for you.

**Comment by Robo210** [comment]
From MSDN's [About Event Tracing](https://docs.microsoft.com/en-us/windows/desktop/ETW/about-event-tracing) (emphasis mine)

### MOF (classic) providers:

- Use the RegisterTraceGuids and TraceEvent functions to register and write events.
- Use MOF classes to define events so that consumers know how to consume them.
- **Can be enabled by only one trace session at a time.**

### WPP providers:

- Use the RegisterTraceGuids and TraceEvent functions to register and write events.
- Have associated TMF files (compiled into a binary's .pdb) containing decoding information inferred from the preprocessor's scan of WPP instrumentation in source code.
- **Can be enabled by only one trace session at a time.**

### Manifest-based providers:

- Use EventRegister and EventWrite to register and write events.
- Use a manifest to define events so that consumers know how to consume them.
- **Can be enabled by up to eight trace sessions simultaneously.**

### TraceLogging providers:

- Use TraceLoggingRegister and TraceLoggingWrite to register and write events.
- Use self-describing events so that the events themselves contain all required information for consuming them.
- **Can be enabled by up to eight trace sessions simultaneously.**

**Comment by vancem** [comment]
Yes, I think we found the 'root limitation'.

**Comment by szehetner** [comment]
Thanks! That will require us to find a work-around, but at least we know where the limit is coming from.
