### ISSUE TITLE
C++ sample to utilize Microsoft.Diagnostics.Tracing.TraceEvent.dll

### ISSUE THREAD

**Issue by hapablanha** [Microsoft/perfview#827]
As C# is built into DLL (Microsoft.Diagnostics.Tracing.TraceEvent.dll), I suppose we can "using" dll and namespace in C++ application. Is there any quick start sample about it?

**Comment by vancem** [comment]
We don't have any C++ samples of using TraceEvent, but in theory it works just like any other C++/CLI application  (see https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=vs-2017)   

Note that since C++ is native code, there are non-trivial ramifications of calling .NET Core (which loads the .NET runtime, along with its garbage collector).    You should worked with this  / experimented with it enough to know all the ramifications of this before committing.
