### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jymcheong** [Microsoft/perfview#889]
### Program Crash 
With exception:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. `

Program's Target Framework is .NET Framework 4.6 

The program runs without exception on the development machine. Exception only occurs on a fresh Win10 VM. 

### Setup Project Warnings

```
------ Starting pre-build validation for project 'Setup' ------ 
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='4.0.1.0') of assembly 'Microsoft.Diagnostics.FastSerialization.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS.IMMUTABLE' (Signature='B03F5F7F11D50A3A' Version='1.2.2.0') of assembly 'Microsoft.Diagnostics.Tracing.TraceEvent.dll'
WARNING: Unable to find dependency **'SYSTEM.RUNTIME.INTEROPSERVICES.RUNTIMEINFORMATION' (Signature='B03F5F7F11D50A3A' Version='4.0.1.0') of assembly 'Microsoft.Diagnostics.Tracing.TraceEvent.dll'**
WARNING: Unable to find dependency 'SYSTEM.REFLECTION.METADATA' (Signature='B03F5F7F11D50A3A' Version='1.4.2.0') of assembly 'Microsoft.Diagnostics.Tracing.TraceEvent.dll'
------ Pre-build validation for project 'Setup' completed ------
```

**Comment by vancem** [comment]
I am not enough of a nuget guru to give you a complete explanation, but I can say:

This is a build time (or maybe deployment time) issue rather than a runtime  or OS issue.  

I am assuming are referencing the Microsoft.Diagnostics.Tracing.TraceEvent package.    

It IS the Microsoft.Diagnostics.Tracing.TraceEvent.dll  that has the reference to System.Runtime.InteropServices.RuntimeInformation.dll.  

When I build a simple .NET 4.6 application using the TraceEvent package, it does correctly determine that System.Runtime.InteropServices.RuntimeInformation.dll id needed and deploys a copy next to 
Microsoft.Diagnostics.Tracing.TraceEvent.dll when it builds it.

This is the one that should be being picked up at runtime.  

Thus you should be copying this DLL along with the Microsoft.Diagnostics.Tracing.TraceEvent.dll when you deploy to another machine.

Are you doing this?

**Comment by jymcheong** [comment]
@vancem Thanks!

For the VS Setup/Deployment project, it did include Microsoft.Diagnostics.Tracing.TraceEvent.dll as part of its auto dependency inclusion.  

The error of missing "System.Runtime.InteropServices.RuntimeInformation.dll" only occurred on Win10 with Dotnet version 4.7.02046 (as per registry). Machines with Dotnet 4.7.03056 & beyond were running fine. 

In the end, I used Nuget to include System.Runtime.InteropServices.RuntimeInformation & the setup project also included System.Runtime.InteropServices.RuntimeInformation.dll. When I did that, the machine that had Dotnet version 4.7.02046 ran the program fine.
